### ISSUE TITLE
Request 2.0 points for the new ships

### ISSUE THREAD

**Issue by Burley50** [raithos/xwing#1124]
Hello, i was wondering if you planned on adding the new ships the clone Z-95, the guanlet and the rogue clas

**Comment by Patschke** [comment]
We do not provide any updates for the 2.0 squadbuilder (raithos.github.io). It would not make much sense to add points from 2.5 for a 2.0 squadbuilder anyway - since the way of squadbuilding is quite different. 

For the 2.5 squadbuilder ([yasb.app](yasb.app)) everything should always be at the latest version, so all of those ships are already added.
