### ISSUE TITLE
Charge counter

### ISSUE THREAD

**Issue by Ras3w** [raithos/xwing#1160]
This is by no means a demand, just think it might be a good QoL improvement. Could a feature be implemented that totals how many charge tokens a given list will need to bring? It would be helpful for getting tokens together prior to travel.

**Comment by raithos** [comment]
I have no personal interest in implementing this. It's honestly easy enough to count the tokens prepping for an event from the list just looking at the print view. Plus if we do that for charge tokens, why wouldn't we also do that for all the other tokens, and it starts to look like more and more work for a small QoL improvement

**Comment by Patschke** [comment]
Maybe I'll consider implementing something like this at some point - since it's not the first time such a request pops up. However, I agree with raithos - you need a bunch of unpredictable tokens anyway (stress, ion, etc - stuff you get from crits, obstacles or opponents), so you'll need a box of "enough" tokens anyway. For charges, force and shields it's somewhat easy to implement showing a precise number, but personally I don't really consider this too beneficial. But again, as I said, perhaps I'll do so anyway because other folks seem to consider it helpful.

**Comment by raithos** [comment]
Ok, so I'm not interested in doing this, if I get a compelling reason I'll reopen. Patrick can do it if he wants but I'm tagging this with wont fix and closing.

**Comment by Ras3w** [comment]
Thanks for the response! I totally understand, it was a very minor QoL
thing.
