### ISSUE TITLE
Banned list visibility in YASB

### ISSUE THREAD

**Issue by starjoe4** [raithos/xwing#1161]
Is there a function in YASB that permits banned cards to be excluded from Extended lists, or at least marked with a red label or something to highlight it?

Once you pick Extended it seems like you can't tell anymore what is and is not banned, and a lot of people are running formats for games that don't permit banned cards in extended games.

Thanks!

**Comment by Patschke** [comment]
I am not sure if I understand this issue. To my knowledge, there is only one banned card in extended (Delta-7B), which is greyed out in extended. There is nothing else banned in extended, so there is nothing to be marked?

**Comment by raithos** [comment]
YASB only supports the official formats. its a hard line because there have been lots of alt formats and since we've become one of the defacto trusted builders of the community, list integrity is important to maintain. as @Patschke stated, the only banned card from extended is the Delta 7b config, everything else is legal. Cards banned from standard are not selectable as intended.

I would consider adding a standard/extended legal info field in the card browser but that's still kind of redundant due to the extended standard filter that already exists.

**Comment by starjoe4** [comment]
I'm drawing a distinction between upgrades that are on the ban list, like Hull Upgrade, Sense and Autoblasters, and ship/pilot combos that are not on the ban list but are not permitted in Standard, like the Starviper or Resistance Bomber.

There are a decent number of extended-without-banned-upgrades games going on out there.  

Would it be possible to add "BANNED" to the text shown for upgrades that are on the ban list, when they're shown in Extended?  Or somehow indicate, when you're picking cards or pilots in Extended, when they are only legal in Extended?

**Comment by starjoe4** [comment]
I wasn't really suggesting a different format.  It would be helpful if there were some kind of indicator or text that makes it clear if a ship or upgrade is on the ban list.  I wish AMG had just limited their list info to "standard" or "extended" because it's confusing to also have a ban list and, as you allude to, effectively creates a third play mode. 

However, being present on the ban list is part of the info on the ships & upgrades now and people do use it, so I was just suggesting that it might be useful to have that information available when listbuilding.

Thanks anyway
