### ISSUE TITLE
The problem of changing translation key name

### ISSUE THREAD

**Issue by kksuke** [raithos/xwing#1163]
When translation key name is changed in cards-en.coffee file, that element's translation is missing, until changing that language resource file(such as cards-jp.coffee), of course.
But another element's translations that replaces later in setupTranslationCardData function of cards-common.coffee are also missing even if there is translation key name of that element.
The impact of changing cards-en.coffee is large.
If you stop rethrowing exception in setupTranslationCardData function of cards-common.coffee, you can minimize the impact of changing the translation key to just that element.

**Comment by Patschke** [comment]
> When translation key name is changed in cards-en.coffee file, that element's translation is missing, until changing that language resource file(such as cards-jp.coffee), of course. But another element's translations that replaces later in setupTranslationCardData function of cards-common.coffee are also missing even if there is translation key name of that element. The impact of changing cards-en.coffee is large. 

I am not sure that I understand what you want to say here. Yes, changing keys has a large impact and should therefore in general be avoided. E.g. if some UI element needs is to be reworded, I advocate for just changing the "english translation" in cards-en (for instance, if you would want to rephrase "Squad Notes" to "Notes on this Squad" for some reason, you shouldn't touch the key IMO). However you can see this as advantage as well: In case something actually changes mechanically, you should change the key (as example, if there would be quarter points instead of half points below a threshold, changing the key "Half Points" would automatically avoid wrong translations showing up).  

> If you stop rethrowing exception in setupTranslationCardData function of cards-common.coffee, you can minimize the impact of changing the translation key to just that element.

Not sure if I simply want that to throw and exception - that's something easy to spot, so you find typos in keys early instead of having to check every card to see if the translation is there?

**Comment by kksuke** [comment]
> I am not sure that I understand what you want to say here.

Sorry for poor English. 
I explain with an example.
I've never changed the key and mostly create PRs for Japanese translations.

When 5fe1761e300965fd15a2152674da16acdfab77be, '"Odd Ball" (V-Wing)' was changed to '"Odd Ball" (V-wing)'.
Under this influence, translation is missing not only Odd Ball (V-wing)  but also all pilots listed below Odd Ball( such as Boba Fett (Separatist), Zam Wesell, Jango Fett...).
In this state, translation becomes useless because most of the text is in English.
The Japanese version is in that state now.

I think the cause is that in the setupTranslationCardData function of cards-common.coffee, if an exception occurs, it will be rethrown and the translation process will be aborted.

> Not sure if I simply want that to throw and exception - that's something easy to spot, so you find typos in keys early instead of having to check every card to see if the translation is there?

Even if we stop rethrowing, an error will be output to the debug console, so we can see the cause.

**Comment by raithos** [comment]
hi @kksuke, sorry about this issue, I renamed a bunch of cards, and the result is as you indicated. I can go through the japanese translations tonight and manually fix all the busted names for the Japanese translation. This is also the last time probably this issue will arise, it happened so i could get all of the ship names and pilot names aligned, but there were some unintended consequences.

**Comment by raithos** [comment]
Oh I see, after rereading what you wrote I think I understand this better. You're pointing out that changing names in cards-common will completely mess up the translation files. Yes, I'm aware of this and this last change was made with me trying to fix all of those issues simultaneously, but I obviously missed a few. I've adjusted things so that they wouldn't need to be adjusted in a major way again for a while. 

Sorry for the confusion about that.
