### ISSUE TITLE
Inventory list error

### ISSUE THREAD

**Issue by mro416** [raithos/xwing#1164]
The inventory list is incorrect for ships
All my ships/expansions are entered correctly, yet the final inventory is incorrect and off by a lot.
Unique number of ships is right, the total is off

a little while ago I noticed that it appeared like many of my ships were deleted from inventory. I added them back but the number is now incorrect 

Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
Can you provide some more details? I recently renamed a bunch of ships which caused those ships to not update their counts properly. This only applies to loose ships added, not ships in expansions. So if you checked your inventory after that you would have noticed that some ships had their counts drop to 0. If you're saying that you updated the ships category of the inventory to adjust things and the final counts are still wrong (basically doubled for ships that you had to go and refix), then let me know, otherwise, its an expected thing to happen, and my apologies about it.

**Comment by mro416** [comment]
Hi,
Yes the problem is that when I went to add the ships back again, it’s now counting them twice
So for instance I have 91 ships, but it’s showing 142 ships at the bottom of the page.

If I counted out each individual ship in the list, it still adds up to 91, but the total at the very bottom shows 142

**Comment by raithos** [comment]
ok shjould be resolved now.

**Comment by mro416** [comment]
Looks good on my end
Thanks for resolving this
Love your squad builder!
