### ISSUE TITLE
Add ship stats just under ship and pilot selection

### ISSUE THREAD

**Issue by dbhoekman** [raithos/xwing#1168]
**Is your feature request related to a problem? Please describe.**
When looking at my squad, it is difficult to remember the stats of the ships that I am flying.

**Describe the solution you'd like**
A small graphic below ship and pilot selection that shows the ships stats

**Describe alternatives you've considered**
The alternative is to hover over each ship one at a time, but you cannot see all ship stats at the same time this way.

**Additional context**
Something like this (the added icons under "Killer":
![image](https://user-images.githubusercontent.com/19825541/193089048-0b51d34a-0865-4045-882f-d75b44bfa748.png)

**Comment by Patschke** [comment]
I am not sure what to think about this suggestion. In the example you show it would not take up much space, but for ships with less upgrade slots (e.g. imagine a droid swarm) it would roughly double the required space on screen - so one might end up with trading "seeing all stats at once" vs "seeing all ships at once". 

So basically, the question should be: Does seeing all stats at a glance is useful for list building? Are you like "hey, I don't have a 1-agility ship yet, better add one to the squad"? For me the stats of a ships mostly seem important, when deciding which ship to add. Afterwards I am not so interested in "Better use upgrade x than y because my other ships have stats whatever". Maybe that's just me though. Maybe it doesn't seem to matter to me, because I know the stats for basically all ships anyway. 

Why is the stat line of specific importance? We could also consider showing other ship characteristics (base size, maneuver dial, actions, etc), but obviously have to pick which ones we show and which ones we don't (and which stuff belongs to ship stats? Asajj with Hotshot Tail Blaster has 7 stat entries, not just the 4 you depict above (3 different attack arcs, shield, hull, agility, force), we'd need space for that as well). 

My personal impression is that I do not want to add the stats to the man view, but perhaps you can convince me that it would be beneficial for the majority of users?

**Comment by raithos** [comment]
right now im leaning into not doing this. i appreciate the idea behind it, but personally one of the things about yasb has been about being as economical about the space as possible. patricks comment about which stats are worth showing is valid, and also how this is more valuable than hovering over the ships which seems just as fast to get the info on the right status bar. ultimately this feels like a feature that could bloat out of control very quickly so im hesitant to just say yes right away.

however, im not going to close it right away, gonna think about it more if theres a solution tha makes sense to me.

**Comment by dbhoekman** [comment]
That's fine!

With regards to space, it seems most the time that space is actually unused
so adding something there wouldn't actually add any additional space being
taken up. Ie you could still be able to view a whole squad.

Yeah I understand that it could get wild quickly with a bunch of
modifications.

The last benefit I would see from it, is to easily determine the balance of
a squad at a glance. For example I could very quickly see that my squad is
way too squishy, and I need to get a ship with more hull, or consider
shield upgrades.

No worries if this isn't something y'all wanna do.

**Comment by raithos** [comment]
So i thought about it more, and I think we're just not going to do it. for the value compared to the amount of work involved, i just dont think its something im motivated to tackle. thanks for your suggestion though!
