### ISSUE TITLE
Pilot Search Via Upgrade Choices

### ISSUE THREAD

**Issue by JediOswald** [raithos/xwing#1182]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to use a combination of upgrades, but with how variable pilots in the same ships can be nowadays I don't always know who can take those upgrade combinations.

**Describe the solution you'd like**
I think it would be nice to have a search feature to find out which pilots are able to equip a number of selected upgrades.

**Describe alternatives you've considered**
Two ways to integrate the feature I have considered is to have either a literal search bar or an option in the ship dropdown labeled "search for pilots" that allows you to select upgrades and shows you all potential pilots. Otherwise the only way to do the process is through brute force looking at every single pilot in the game.

**Additional context**
YASB is the best squad builder out there! Thank you for what you do Raithos!

**Comment by Patschke** [comment]
Can you elaborate why the existing search functions in the card browser are not sufficient for what you want? It does not accept a list of specific upgrades, but you can search for pilots featuring a given set of slots - which should be good enough for most cases? 

For instance if you want to know who can haul proton bombs forward with a 4-straigth by combining trajectory simulator, skilled bombardier and proton bombs you can't search for the specific upgrades, but selecting payload, gunner and system slot gives you basically the same answer (in that case: most (or all?) TIE/ca Punisher and MG-100 StarFortress pilots and specifically R2-D2 in the BTL-B Y-wing). I've implemented the advanced search about four years ago, but of course, feedback is still welcome!

Searching for all ships that can equip specific cards might be harder than you expect, since there are a lot of edge cases that are somewhat ambiguous (just to give an example: Who can equip 0-0-0? Does that require a ship to also have a crew slot available for Vader, or is it fine if we assume that Vader might be on another ship?)

**Comment by JediOswald** [comment]
Dear Raithos,

I’m sorry for this, but I did not know this was already a feature! Please disregard then.

**Comment by Patschke** [comment]
Glad I could help. We're always happy to receive feedback, so don't worry to open an issue again if there is anything you want to suggest or ask about. (Just as a note: I'm not Raithos - but since I neither have Twitter nor Facebook, I can see why people are not aware that he's not the only Dev of YASB. Apparently having social media is what defines existence these days 😉)
