### ISSUE TITLE
Authorize points overrun

### ISSUE THREAD

**Issue by JeremTGB** [raithos/xwing#1186]
Hi,

With the point upgrade, some players are unable to upload their list in our last tournaments that happened before.
Since List fortress only accept Yasb url, it would be great to have an option to allow point overrun. 
Maybe flash the points in red to feedback the issue in the builder but still allow it for the issue above ;) 

Thx!

**Comment by Patschke** [comment]
You can use yasb.app/old for old lists (and perhaps remove the /old when entering it in list fortress). I don't know how List fortress works internally (if it actually uses YASB to check if the list is legal then it is probably intended, that we do not allow illegal lists), but if it just parses the squad code from the URL this could work.

We do not intend to allow building any illegal lists in YASB.

**Comment by raithos** [comment]
if they use the same parsing tools that I think they're using, adding the replacing the yasb.app/ part of the link with yasb.app/old/ should work, since its only parsing the arguments and not the whole link. As said, we're not going to allow for illegal list building since many use YASB to validate lists as well.

**Comment by JeremTGB** [comment]
Thx. We will try this!
