### ISSUE TITLE
New Pride of Mandalore Quickbuilds

### ISSUE THREAD

**Issue by Raymixx** [raithos/xwing#1194]
Hi! I really enjoy YASB for planning squadrons for Star Wars: X-Wing. I only play casual and mostly with quickbuilds (the people I often play with don't want to wade through quagmire of upgrades in order to play). I noticed the quickbuild cards for the pilots from the "Pride of Mandalore" expansion are not yet available in YASB. Would it be possible to include those? I'd be happy to send you scans of my copy of the cards if you need them. Thank you for your help!

**Comment by Patschke** [comment]
If you could provide those I'll add them. Sadly there is no official source for a list of all Quickbuilds. I usually grab them from time to time from the wiki, but they aren't listed there up to now ([wiki Pride of Mandalore](https://xwing-miniatures-second-edition.fandom.com/wiki/Pride_of_Mandalore_Reinforcements_Pack?#Additional_Information) vs [wiki Hotshot Aces](https://xwing-miniatures-second-edition.fandom.com/wiki/Hotshots_and_Aces_Reinforcements_Pack?#Additional_Information). 

As YASB is open source you could also add them directly yourself - it's not difficult to do just tedious ;-) If that might be an option for you I can help you on how to do this (as a first starting point: They are a listed [here](https://github.com/raithos/xwing/blob/master/coffeescripts/content/cards-common.coffee#L26214), currently YASB has 620 quickbuilds.)

**Comment by Raymixx** [comment]
I think I can add them myself if that’s alright with you. I took a look at the format and it seems to be fairly easy to follow, especially since I’m not adding new cards. Does the quick build ID number have significance (should I add these cards before the Gauntlet Fighter ones because they were released first)?

Raymixx

**Comment by Patschke** [comment]
You should just add new consecutive IDs for the new Quickbuilds. The ID is e.g. used to save a squad and is part of the URL, allowing easy sharing of squad lists. If you would change the IDs of the existing Gauntlet fighter, people would be surprised when opening their Gauntlet-Quickbuild-Squad, since those would have magically been converted to pride-of-mandalore Quickbuilds.

I'm not sure if or how familiar you are with git(hub), so here's a short summary: You won't have direct write access to the file above (sadly the internet is not filled with kind people, so that wouldn't work in general). Instead you have to a) "Fork" the repository (there is a button on the top right). This creates your own working copy. b) within your fork you can edit the required file (there is a web-editor, so you can do it in your browser. You also have the option to "clone" the repository to your hard drive and edit the file on disk with whatever editor you like. In that case you need to "push" the changes to the server after you are done). c) create a "Pull request" (there is a button near the top left for this). This will basically give us the option to copy over your edits (containing new and exciting Quickbuilds). The benefit of this workflow is that you can't break anything, no matter how hard you try ;-)

 I'm always happy if somebody contributes code directly (less work for me :P). If you have any questions feel free to ask.

**Comment by Raymixx** [comment]
Sounds good to me! I just finished my contributions and created a Pull Request for them. Hopefully I did everything right and it turns out ok. Thanks!

R

**Comment by Patschke** [comment]
Yep, everything looks right. Can be merged and should go live with the next update. 

Thanks for contributing!

![grafik](https://user-images.githubusercontent.com/17853362/201494760-827e881f-8909-432e-a6ff-61bb80421bd7.png)
