### ISSUE TITLE
StarViper-class Attack Platform Missing from Scum/Villany List

### ISSUE THREAD

**Issue by Goveyscout** [raithos/xwing#1211]
I cannot find the StarViper-class Attack Platform in the scum and villany choice for ships. It is not in any of the other factions as well.

**Comment by raithos** [comment]
did you switch to extended in the game mode? the site defaults to standard

**Comment by Goveyscout** [comment]
Let me try that. What is the difference? Sorry new to xwing.

**Comment by Patschke** [comment]
Those are different game modes where different ships and cards are legal. Basically "standard" includes only ships that have been released since start of the 2nd edition, while extended also has all the ships from first edition (that can still be played just fine using a conversion kit). The idea behind limiting the ships in standard seems to be that new players should have the same options available (while possibly being unable to buy the first edition ships, as they are out of print).

**Comment by Goveyscout** [comment]
Ok, thanks for the clarification.
