### ISSUE TITLE
Multifaction restricted upgrades

### ISSUE THREAD

**Issue by nitrobenz** [raithos/xwing#1248]
**Describe the bug**
 in multifaction mode I cannot add upgrades with the “squad including x” restriction to ships outside its native faction.

**To Reproduce**
1. Go to multifaction option
2. For the first pilot Select TIE/x1 with Darth Vader pilot
3. For the second pilot Select VCX-100 with “Chopper” Pilot
4. Under VCX-100 crew upgrade drop down look for 0-0-0 at (5) points
5. 0-0-0 is not in the crew drop down

**Expected behavior**
0-0-0 for example can be put on Morna Kee decimator if Vader x1 is a wing mate, but 0-0-0 cannot be put on “Chopper” VCX-100  with Vader x1 as a wing mate. Same for Maul crew, which cannot be put on non-rebel ships even though Ezra elsewhere in the squad should enable it.

**Screenshots**
![F4138843-6ED5-40C7-8E67-448E5A922B27](https://user-images.githubusercontent.com/104114780/225081040-f9d03150-dca8-4478-a9c6-d0627fbc6289.png)
![A92D3BE4-A290-4165-9F48-981B090AA6D5](https://user-images.githubusercontent.com/104114780/225081051-5637970e-4578-4d89-9a05-1c820dfd8f99.png)
![716E8076-32B8-4022-8026-1AE7C254CD72](https://user-images.githubusercontent.com/104114780/225081056-67ccb8c1-7ef2-49db-9b04-4ed1fb01d87c.png)
![A46594AC-B1FF-4A8B-B78C-694866AE9109](https://user-images.githubusercontent.com/104114780/225081058-410b6732-4413-4529-8610-9916905c3191.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: firefox, safari
 - Version 110.2

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - OS: iOS16
 - Browser: Firefox, Safari 
 - Version ?

**Comment by raithos** [comment]
Ok, so this is a thing that I wont be resolving. The main reason is that these have also been restricted to the factions that can use them, even though the restriction is by personnel. This is so those crew don't show up in every faction, with no way to actively equip them. Resolving that for multi-faction is something I'm not interested in fixing at the moment, since multifaction lists are not tournament legal and these are the only 2 exceptions that have this restriction at the moment.
