### ISSUE TITLE
Wampa (BoY) coming up as unreleased content

### ISSUE THREAD

**Issue by TheMightyAnt117** [raithos/xwing#1316]
**Describe the bug**

**To Reproduce**
1. Got to The empire Tab
2.  click on Add ship
3. Scroll to tie fighter/ln and add wampa **(BoY)**
4. Says wampa(BoY) is unreleased content

**Expected behavior**
Not to get a warning that my list includes unreleased content
**Screenshots**
![image](https://github.com/raithos/xwing/assets/36612584/0c911a38-145c-4a4c-bb59-16dc10bf462f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
Well, the actual issue is that upgrades like Wampas Vengeful do not exist as upgrade card, but are implemented as if they'd be a real card. If we added them to the content of the expansion packs, they'd be counted as if people had the cards (e.g. they might build a squad that contains Elusive as usual upgrade card on another ship, as YASB believes they own a copy if they own Wampa). If we don't add them as part of the pack, special cards like that Vengeful pop up as unreleased. So while the warning technically is that no card "Vengueful (BoY)" exists, you are of  course correct that this behaviour is not great. 

I guess what we should really do is tagging standard-loadout upgrades in a way that prevents them from counting against collection content and release status...

**Comment by raithos** [comment]
yup, the solution is to exclude upgrades on standardized cards from being checked against collection. that would also be the case for situations where normal upgrades exist on standardized cards but you down own that card either.
