### ISSUE TITLE
Incorrect damage thresholds

### ISSUE THREAD

**Issue by NorixiousB** [raithos/xwing#1330]
While exporting lists via text, the listed damage threshold to get half points on ships with odd values of combined hull and shields is rounding down when it should be rounding up.

I've seen this with;
Resistance T70s, listed as 3 and should be 4
Empire TIE Advanced X1, listed as 2, should be 3
Empire TIE/Interceptor, listed as 1, should be 2.

**Comment by Patschke** [comment]
I have to admit, that for me this value was never really helpful. Is "damage threshold" referring to "you score points, if the ship has that much damage taken" or "you score points, if the ship has that much HP left"? Depending on the answer to this question, one should round up or down. 

The behavior you describe is, as far as I'm aware, what we have always used for YASB. It's the case for all ships and all types of export (not only for the text version).

**Comment by NorixiousB** [comment]
Fair points considering the ambiguity when its written out, especially considering I had to refresh on the definition of threshold before submitting the issue. 

I've never run into the issue on the table so I guess that brings up another question of why have the value listed at all if it can be taken either way and generate confusion?

**Comment by raithos** [comment]
This definition of threshold was made to be in line with the official builder. threshold is basically how much damage you could take and not take half points on. this is technically correct as that lines up with the literal definition of threshold, but not how normally we think of the value, so I get the confusion. It's still a value that is used in game since we use it for chance engagement, so I'm not planning on changing anything at this time.
