### ISSUE TITLE
Upsilon command shuttle 

### ISSUE THREAD

**Issue by Mosxutus** [raithos/xwing#1345]
The Upsilon command shuttle ship option for the First Order faction, is not available to select in standard format. However, having checked the banned and restricted list (last updated on  09/08/2023), the ship should be available. Am I missing something? **Is your feature request related to a problem? Please describe. 

**Describe the solution you'd like**
Make the Upsilon command shuttle available to the First Order on standard lists 

Thank you for your time and invaluable service,
Nick

**Comment by Patschke** [comment]
It's not banned, because it's just not legal. Banned cards are cards that have been released since second edition but removed from the game. Not legal are all ships, where the model has not yet been released in the second edition (so you can have a 1st edition ship plus conversion kit, but 1st edition ships are not available on the market anymore, so it would be unfair to include them for tournaments). The Y-Shuttle is such a case. 

It has a simple "No" in the standard-legal column:

https://cdn.svc.asmodee.net/production-amgcom/uploads/2023/09/Ship_Points_09.08.23_v2.pdf
