### ISSUE TITLE
Not Linking to Facebook

### ISSUE THREAD

**Issue by airfugitive** [raithos/xwing#1355]
**Describe the bug**
My account is tied to Facebook and I have not been able to access my lists due to an interface error between YASB2.5 and Facebook. 

**Expected behavior**
When logging in an clicking on the Facebook option, I expect to see a sign in for Facebook. However, it is saying "Error Accessing App
We're sorry, but the application you're trying to use doesn't exist or has been disabled."

**Desktop (please complete the following information):**
 - Chrome and Safari browsers.

**Comment by raithos** [comment]
I have some bad news... it seems like Facebook has disabled their oauth login API to business accounts only. After a lot of searching it seems I can't set up the api at all as an individual, and I don't have a personal legal business to attach to it. This leaves facebook login out of the question. I'm sorry this is not the news you're looking for, but it seems like your account info is locked. 

I can attempt to transfer all of your list information if you remember some of your lists, but it would require a dialog between us. Best chance is to contact me on discord, @raith and see if I can help you get set up. Otherwise your best bet is to rebuild from scratch.

**Comment by airfugitive** [comment]
That stinks. No worries, I was actually in the process of taking the current inventory and moving it to excel spreadsheet. My New Year’s resolution was to use every card this year. I’ll set up another login and and re-enter the inventory later. Thanks for looking into it!DanSent from my iPhoneOn Jan 12, 2024, at 20:07, raith ***@***.***> wrote:﻿
I have some bad news... it seems like Facebook has disabled their oauth login API to business accounts only. After a lot of searching it seems I can't set up the api at all as an individual, and I don't have a personal legal business to attach to it. This leaves facebook login out of the question. I'm sorry this is not the news you're looking for, but it seems like your account info is locked.
I can attempt to transfer all of your list information if you remember some of your lists, but it would require a dialog between us. Best chance is to contact me on discord, @Raith and see if I can help you get set up. Otherwise your best bet is to rebuild from scratch.
