### ISSUE TITLE
Chinese translation support

### ISSUE THREAD

**Issue by MasterShuang** [raithos/xwing#1388]
Hi,

I'd like to help support the Chinese, and I have all translated text, please email me at 65490836@qq.com and we can see how I can fit your format.

Regards,

Gary

**Comment by raithos** [comment]
Hi Gary, 

If you put the translations into this file (attached), then submit it into the translations directory for approval we can get the Chinese version live. The file is zipped so that it can be attached in GitHub. Just replace the Japanese text with your translations and keep the syntax the same, mind the ' and " and keep the spacing exactly the same as in the format. 

[cards-zhcn.zip](https://github.com/raithos/xwing/files/15284046/cards-zhcn.zip)
