### ISSUE TITLE
Squad(s) not loading

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#140]
### Expected Behavior

Load the squad via the following link:
https://raithos.github.io/?f=Scum%20and%20Villainy&d=v4!s!138:-1,168:-1:-1:U.11;159:101,95,108:-1:-1:;159:101,95,108:-1:-1:;139:-1,168:-1:-1:U.11;139:-1,168:-1:-1:U.11;139:-1,168:-1:-1:U.11&sn=IonSwarm&obs=

### Actual Behavior

Not doing anything. (blanc YASB without any way to add ships etc)
Similar issue with different squads as well.

### Language

All

**Comment by raithos** [comment]
It looks like your URL is not conformed to the format of the ship. How old are these lists? We made changes to the M3A a while ago which I see your list has. Here is a reconstructed list based on the url you provided

https://raithos.github.io/?f=Scum%20and%20Villainy&d=v4!s!138:-1,168:U.11;159:101,95,108:;159:101,95,108:;139:-1,168:U.11;139:-1,168:U.11;139:-1,168:U.11&sn=IonSwarm&obs=

I'm not going to be able to manually reconstruct every list you may have made, but if the list doesn't load, it would good to let me know what ships are in that list to confirm those are ships that had their configuration changed. Unfortunately there isn't anything we can do to fix this since the changes to the config were necessary to fix other major issues. Sorry for the inconvenience.

**Comment by Patschke** [comment]
Fixed in #142

**Comment by Patschke** [comment]
It was a real issue. The link explicitly contains the information "no title" and "no modification". However, as titles and modification have been merged into upgrades a while ago, that information is not needed anymore. It should of course still be okay to provide this useless information - and it with the above PR.

**Comment by tinitaet** [comment]
Thanks to Patschke!
@raithos the matter is, that I build my squads a couple of weeks ago, saved the links for later and now they didn't work. The issue is, that many people do this quite often and so stuff like this should be fixed.
