### ISSUE TITLE
Custom load out Biggs missing torps slot

### ISSUE THREAD

**Issue by CloakerCobra** [raithos/xwing#1405]
Bigg missing torps slot 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
Biggs is not supposed to have a Torpedo slot. According to the latest [AMG points document](https://cdn.svc.asmodee.net/production-amgcom/uploads/2024/02/SWZ_Ship_Points_02.23.24.pdf), he's just having Astromech, Modification and Configurations slots. 

Perhaps you are missing the slot, because we (wrongly) had him given one and fixed that just recently with #1401 ?

**Comment by CloakerCobra** [comment]
Weird, Launch Bay has him with torps

Seems like a mistake to give Biggs 18 load out and no torps

Thanks!

**Comment by Patschke** [comment]
Yep, he has no way of spending more than 16 of those points (using R2-D2 and either afterburners or shield upgrade). Obviously, it seems like a mistake where somebody has done something wrong there, but as we just implement the official points that's what we currently have :shrug: 

So I guess that's somewhat a "bug" on the AMG point document, feel free to ask them to fix it? It's not a new bug though, as it was already like that on the [september 2023 point document](https://cdn.svc.asmodee.net/production-amgcom/uploads/2023/09/Ship_Points_06.09.23.pdf) as well - we just had it wrong in YASB (and LBN still has it wrong as it seems). Back in 2022 he had a torpedo slot (but only 12 points of loadout. So I guess when updating to 18 loadout, we didn't notice the slot change)...
