### ISSUE TITLE
Dual List Building

### ISSUE THREAD

**Issue by zxwnek** [raithos/xwing#1426]
**Describe the solution you'd like**

I'm not sure if this exists yet or not, but I'd love  away to compare two lists in a way that I can see the Ship stats (movement dial not necessary) and compare them. I do this to setup (relatively) balanced games for new players. 

I know that I can print lists, and using two windows but it looks a bit messy (maybe alternate view options would help this) and I wonder if there is a solution would make dual list-building a bit easier.

Also, is there a way to set the default Ruleset to XWA Beta? Or will that become the default after Worlds?

Thanks for your work on XWA, YASB and your support in the X-Wing community.

**Comment by raithos** [comment]
XWA rulesets will be come default after Worlds, which one is up to the XWA committee to decide. Until worlds though, we will still have AMG points as standard. As for your other request, unfortunately, a compare list is a feature set that I have no intention of implementing, due to the massive amount of UI frontend work to make something like that work.
