### ISSUE TITLE
Quick Builds

### ISSUE THREAD

**Issue by ywingpilot45** [raithos/xwing#158]
How about adding a quick build opinion?

**Comment by raithos** [comment]
It depends on what we're talking about. If you're talking about FFG official quick builds, sometimes ships dont follow the loadout the ships actually have, so that won't work unfortunately with YASB. Ultimately that would be a completely separate builder. if you're talking about common ship loadouts, we'd need a database like list juggler to provide those common ship configs, and we'd run into the problem of if FFG changes the loadouts, those ship configs being out of date, as well as find a place in the layout to put it (I'm super wary about adding new features that clutter the layout, as its one of the main advantages of the builder). this is a potentially good idea but lots of challenges

**Comment by Patschke** [comment]
Well, it would be a "completely sepearte builder", but a quite simple one. We would basically keep the ship/pilot selection part, but as no upgrades can be choosen, we'd only need to display the upgrades instead of having any sort of builder there. I am not sure how Quickbuild handles uniqueness, but beside of that I am pretty sure that no build rules have to be checked. 

I'd suggest adding a quickbuild option to the Standard/Second Edition dropdown, so the layout would remain unchanged. 

It would of course require some work to do that, but I don't think that it would be impossible, or much easier to setup a quick build only squad builder. We would need to store somewhere which upgrades belong to which pilot, and cannot simply display those upgrades on the ship using the current upgrade selection code - as the upgrades may not follow the rules. As it would be pointless to display any slots not in use as well, it would anyway be usefull to swap out the upgrade selection with some upgrade display.

**Comment by raithos** [comment]
Yeah. All of that sounds like way more work than its worth, considering that Threat cards were meant to be really easy to mix and match, essentially something you could use instead of a builder in the first place.
