### ISSUE TITLE
Grey color makes Fancy View stats bar real hard to read when printing.

### ISSUE THREAD

**Issue by Laurvin** [raithos/xwing#179]
### Expected Behavior

Fancy View bar with Ini, Arcs, Agility, etc. is not very readable on printouts.

### Actual Behavior

Even when printing in color the dark grey of this bar makes it hard to see the numbers and actions in this bar. When printing in black and white it's even harder to see. Could this bar be changed to a really light grey or even just have an outline and no color fill at all?

### Language

All

**Comment by Patschke** [comment]
Did you actually uncheck the "Print color" box for the black and white print? Or did you just use the colored version, and printed it black and white using your printers settings?

**Comment by Laurvin** [comment]
>  Did you actually uncheck the "Print color" box for the black and white print? Or did you just use the colored version, and printed it black and white using your printers settings?

A friend of mine printed them; one was a color version printed in color and the other was a black and white version by mistake.

**Comment by raithos** [comment]
printing a color version on a black and white printer does look hard to see, but that's why there is a black and white option. I have not heard anyone else have issues looking at the printouts after a month of asking. For now I'm going to close this topic, if I hear sufficient feedback that it is an issue, I can reopen it.
