### ISSUE TITLE
Daredevil not appearing for the X-Wings

### ISSUE THREAD

**Issue by kburgbob** [raithos/xwing#200]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

The Daredevil talent should appear for X-Wings when they have the S-Foil configuration card, since when their S-Foiks are closed, the get the boost action.

### Actual Behavior

Daredevil is not selectable.

### Language

The affected language(s). 

English.

**Comment by raithos** [comment]
I would want a rules clarification on that before implementing. While the official app works that way, that seems like an unintended interaction and also not how FFG used s-foils in 1.0. I'll keep the ticket open until we get more clarification, if it is indeed the way it works I'll change it.

**Comment by raithos** [comment]
Upon a much more detailed look at the rules, it appears there is no written reason why it shouldnt work. I still believe its an unintended interaction, but we would need FFG to officially rule on that, and since thats less likely, I just implemented it so that daredevil (and expert handling now on the t-70) will work with the closed sides.
