### ISSUE TITLE
Biohex Codes arent hyperspace legal, but you have them in there as hyperspace legal

### ISSUE THREAD

**Issue by sacimino23** [raithos/xwing#222]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
We have listed Biohex Codes as not Hyperspace legal since 0facf096b6db6178748d57099dd66fb0e6f3b749 which is already online. For me Biohex Codes does not show up when selecting Hyperspace mode. Please try to reload YASB, and check again if you did select the correct game mode. I am unable to reproduce this bug.

**Comment by sacimino23** [comment]
Huh, yea its not there anymore. reloading dropped them out. Thanks!
