### ISSUE TITLE
Print Layout easy/fancy

### ISSUE THREAD

**Issue by dschaust** [raithos/xwing#262]
Hy,
is it possible to make an option in the simple text mode or in the fancy mode to see the ship stat`s in a way you see in the picture?
Because there are no more informations of the ship stat`s and availabe actions on the ship base pat, the simple Layout is a bit to simple ;-)

Maybe it`s possible to create a checkbox in the fancy mode to skip the text of the upgrade cards. Or you can add the stat`s and actions of the ships in the ship/pilot field in the simple mode.

![simple-fancy](https://user-images.githubusercontent.com/46677551/51114530-dccf7f80-1805-11e9-9856-989410b5bdaa.JPG)

Thanks! Keep up the great work!

**Comment by Patschke** [comment]
Both options would be possible. 

When adding the actions and stats to the simple layout, I'd probably just add a line between the pilot/ship name and the upgrades, containing stats and actions as icons in black - so it matches the simple style. 

If I'd add an skip text option for the fancy layout, there would still be the corresponding slot icon next to each upgrade, the point costs might remain in some circle, and the names/stats/action bar would be the layout presented in your picture. It would also be colored by default. 

However, the basic idea of the fancy layout is to present all required information, so that it could theoretically replace your cards and is easy to understand for new players, while the simple layout tries to only show what is needed for a tournament organizer...

**Comment by dschaust** [comment]
Because personally i like the fancy style, the version with skipping the text would be my favorite. The point is, that the most squad`s need 2 A4 paper`s. That need more space than the original Card`s. As the player normally you know the Pilot skills an the upgrade cards. With the "skip option" you can print the list in the way you want. Simple, simple/fancy hybrid an fancy with all the text.

As you say the list with all the text is for new players even clearer than the cards i think.

**Comment by raithos** [comment]
its not just for new players. many veteran players use it as substitutions for bringing lists to local events or game nights to replace bringing their cards, as well as for playtesting purposes. Personally to me it doesn't make sense to not exclude the gametext since if you're using fancy mode for any of the uses mentioned above, you still need the space for tokens and damage cards anyways, so you want that extra space regardless.

**Comment by Patschke** [comment]
![grafik](https://user-images.githubusercontent.com/17853362/51165542-dc37f700-18a0-11e9-901b-64e834139fc7.png)

Is that what you wanted?

**Comment by dschaust** [comment]
@ raithos: yes of course. I think it can be an option. My situation at the moment is, that i play a four ship list and train it for a tournament. So i know the skills, but sometimes i´m confused with the actions. Also all of my sparring partners know the skills of the pilots and the upgrade cards. With the layout patschke show`s, there is place for markers and it is smaller than the cards or the full fancy mode.

@ Patschke: Exacatly

**Comment by Patschke** [comment]
The checkbox option for that layout is included in #263. So it will be available, if that PR goes live.

**Comment by dschaust** [comment]
Yeah cool. Thank you! 
You do a good job guys, keep it up!
