### ISSUE TITLE
Card database

### ISSUE THREAD

**Issue by Oeenn** [raithos/xwing#265]
It would be cool if there was a card database like the FFG squad builder, and the FFG builder is trash. I very much prefer YASB. If you could get a card database it would improve it a lot.

**Comment by Patschke** [comment]
We do have a great card database with some powerfull search functions on hand. Just hit the card browser button right next to the faction selection icons. 

You can close this issue if this is all you asked for, or specify further what you want to be included to the card browser that currently does not exist.

**Comment by raithos** [comment]
yeah, im going to close this for now. our card browser also works with collections as well if you're logged in, its a really good way to check if you own an item if your collection is up to date. As @Patschke said if you have an issue reply here. I'll reopen the ticket in that case, otherwise, this is a feature we already have

**Comment by Oeenn** [comment]
does it have pictures of the actual cards?

**Comment by Patschke** [comment]
No, but it does show all information. Please just have a look at it yourself, and leave some feedback if you have any ideas on how to improve it further.
