### ISSUE TITLE
Request - Display Pilot Int without mouse-over

### ISSUE THREAD

**Issue by cm5089** [raithos/xwing#276]
## YASB 2.0 Feature Request

It is useful to see the initiative makeup of your squadron while selecting pilots - and correspondingly to see the int values of the pilots in the drop down list.

### Requested Behavior

1. Add pilot initiative to drop down pilot selection.
2. Display initiative for currently selected pilots next to their entries, without needing to mouse-over the drop-down.

**Comment by Patschke** [comment]
Well, I am not sure if that is actually a good idea. I'd prefer to have all information on one place, which currently is the mouse over beeing displayed on the right side. 

For the selection of a ship, it would e.g. also nice to see all the stats - but displaying them along with the ship name would cause the drop down to become quite messy. 

Having one number on the drop down (currently the point costs) seems to be enough for me, as an increasing amount of numbers will make it more difficult to tell, what they actually show. A drop down is no table, so one would need to show it like `Miranda Doni (INI: 4, points: 48)` which is quite a long name. 

If you are interested in finding pilots that match a list where initiative matters, I'd recommend using the card browser, located beside the faction selection on the top bar. The browser is able to filter nicely for initiative, so you can easily find all pilots with some specific initiative, regardless of the ship type.

**Comment by cm5089** [comment]
Mouse over is nice but if you use a mobile browser it's borderline
unusable: long press on the screen, cancel the drop down, scroll past all
the other entries WITHOUT TOUCHING ANYTHING ELSE or you'll bring up a
different mouse over screen before you see it.

Stat lines for ships don't change between pilots - the pilot int is
different, unless you can recite the int values for each of the T70 pilots
(both generic and unique) by heart?

It's also not exactly bloating to include an extra number in the text. I
agree your example was excessive but how about:

Academy Pilot (23)

Vs

1 - Academy Pilot (23)

As for having the information in one place why would you have to remove it
from the mouse over page? The drop down is a summary - would you remove the
pilot name because it's listed in the drop down?

Finally the card browser is underdeveloped and, again, is not designed for
mobile.

**Comment by Patschke** [comment]
I agree that our current design is not suited well for mobile user. Having the mobile view in mind was an information you did not provide before, thus I did answere with the desktop site in mind, which has no real need for displaying more information in the drop down. 

I am always happy to receive some constructive feedback on how to improve the mobile view, as I have not come up with a way that I'd personally really like yet. Obviously the mouse over should be entirely dropped for the mobile view, but I am unsure where to put which information. I could probably add the ship stats (hull, shield, attack, agility, base size) to the ship dropdown. That would make each ship using two instead of one line, which still seems okay. Having the maneuvers added there as well would cause the dropdown to get probably too messy? I am not sure about where to put the actions either. For the pilots, I need to find a spot for Ini, upgrade slots and pilot abilities. There could be some information beeing displayed permanently after a ship/pilot/upgrade has been selected, but that would reduce the clear structure of yasb that I'd like to keep...

If you have any usefull feedback for the card browser, I'd be happy to receive that as well. 

I want to remind you, that (unlike the official ffg app devs) nobody is beeing payed for developing and maintaining yasb. Thus, it might be more likely that someone spends his free time to implement a feature requests, if you ask friendly and explain why a feature would be usefull.

**Comment by LordVorKon** [comment]
I'm sorry, but I must respectfully disagree.  I use the mouseover panel a lot, even on mobile.  Perhaps I have gotten lucky with my choice of platform (I use Chrome on Android) and the site doesn't work as well with other choices, but I have been using YASB on a smartphone for quite some time now with very few problems.

I have thrown together a very quick-and-dirty pdf with a couple of screenshots that may help illustrate where I'm coming from; it can be found [here](https://www.dropbox.com/s/jm5w6d1dyh64a78/YASB-mobile.pdf?dl=0).  I will also mention that for browsing purposes or trying to compare two pilots, not having any other ships below the one you're looking at helps.

As for the card browser, a second dropdown might help.  For example, if you select "Type (by Name)" in the "Sort cards by" dropdown, then the second dropdown only has card types.  This could even have multiple options for some types, particularly pilots which could be split up by faction, for example.  Once you select a type, then you get a list of cards that you can select to see their details.

**Comment by LordVorKon** [comment]
I should note, I'm not opposing the idea that Initiative values be added to pilot dropdowns; I'm only opposing the idea that the mouseover ought to be removed from mobile.

**Comment by Patschke** [comment]
In my opinion one basic idea of the mouse over information bar on the side is seeing all information during the selection of a pilot/upgrade, while still having a compact selection area. It does not fulfill that purpose on mobile devices, as you need to scroll down elsewhere to actually see the information. Even if one can get used to that fiddly scrolling, I believe we agree that it is not an exactly good solution. So basically one need to drop one of the two aspects (compact vs. all information visible) on mobile views, as the screen size is limited, and comit into optimizing the other: 

a) having all information available while selecting: This could e.g. be achieved by larger dropdowns containing more information, but will make them less compact. The dropdown size could be reduced by displaying some stuff after the selection, but I don't like this as it will reduce the compactness of the squad view. 
b) not having the information visible during the selection: It might e.g. be possible only showing them as modal dialog, perhaps after one hits an ⓘ icon available next to each card name. The basic idea in this case would be, to replace the scroll-down-to-the-bottom action by some more reasonable one.

**Comment by LordVorKon** [comment]
Alright, I see where you're coming from.  I still don't think the current setup is that big of a deal, but I'm willing to accept I might be in the minority with that opinion.

Of the two options you have presented, I believe I would prefer (B).  However, instead of having an info-button for each card (which will take up a non-trivial amount of screen space and/or be too small to reliably select), might it be reasonable to have only two?  One for the ship/pilot, and the second for all of the equipped upgrades.

I realize that the second dialog will end up quite lengthy when a ship has a large number of upgrade equipped, so another option might be to have three buttons: one for the ship/pilot, the second for the left column of upgrades, and the third for the right column of upgrades.  I have no idea how much of a pain that might be to code, though, given that changing pilots often changes where some or all of the upgrades end up.

In either case, I feel like a good place to put these info-buttons would be to one side or the other of the ship's squad point total, since there's space there that is currently unused.

**Comment by cm5089** [comment]
This issue does appear to be diverging into the overall suitability of the mobile app - I agree it could be improved but as @LordVorKon said, it's perfectly serviceable.  I'm not suggesting changing or removing anything from the mouse-over display, only adding to the summary entry (and maybe the load squad page, see point 1 below).  My original point was actually multi-platform:

1) You can't glance at the squadron builder and see the initiative make-up of a squadron, you have to mouse-over each pilot.
- This affects both the main view *and* the 'load squadron' page where it would be very useful to have this information.
- The INT make-up tells you a lot about the squad - 554 - arc dodgers - 111114 - Drea Swarm etc.
- It's useful to see all INTs when building a list, it makes it easier to see how ship interactions are going to work.
- It's very hard to view on mobile.

2) Secondly it would also be useful to know see the INT of a pilot in the dropdown summary before you select.
- Gives you an overview of the INT breakdown of the available pilots for a ship. Very useful for ships like the TIE LN and T-70 which have a lot of uniques and generics.
- This happens to partially solve issue 1) and the issue on mobile screens because the INT would be shown in the summary.
- The change is small and an 'easy win'.

Hopefully this makes my original intent clear.  Apologies for my initial response if it seemed unfriendly - I work as a software consultant and have a bugbear about developer responses that boil down to 'I disagree, you're using it wrong' without seeking further information.  It usually means the user hasn't expressed himself clearly enough or that the developer has misunderstood.

**Comment by Patschke** [comment]
Ok, so I'll implement an option to show the INI in front of pilot names. I personally do not need that (maybe because I indeed know the values for almost all pilots? But I see, that I am probably part of a minority with that...), so having an option to choose will not hurt for sure. 

For the load squadron page: 
Do you think we should display that for every squad, or are people able to add the INIs to the squad name in case they are relevant for that specific squad? You convinced me adding the option for the actual squad building, but I am unsure about the squad loading...

Thanks for your feedback!

**Comment by cm5089** [comment]
Thanks a lot!

With the load squad page I am not sure - my instinct would be that initiative and points total for the ship would both be useful, especially given the points changes about to happen but I don't think it matters as much.  You can load the list to view the specifics.

Incidentally when you update the points will it be reflected in the points cost on the loading screen?

**Comment by Patschke** [comment]
Unfortunately they will not update on the loading screen, as the squad is only beeing checked on loading, and the data it was stored with is beeing displayed in the list.

**Comment by Patschke** [comment]
Should only the drop down contain the Initiative, or the actual selection, too? 
![grafik](https://user-images.githubusercontent.com/17853362/51849380-dec63200-231f-11e9-8d53-b3d98d93e0ad.png)
![grafik](https://user-images.githubusercontent.com/17853362/51849469-17660b80-2320-11e9-85d9-3a2e3bc66d8d.png)

Regarding the pilots on the squad loading screen: There is actually a description beeing stored along with each squad, that by default contains the names of the pilots. On the loading screen, that description is beeing displayed again, but not checked or modified at all - in fact, if you store your squad using one language, the squad will always be displayed in that language (but loaded in your currently selected one). The same holds for the points of the squad. I don't think that we want to load all squads somewhere in the background each time you open up the loading screen, as that might influence the performance quite negatively on slower systems. Maybe we can store the creation date, and display a warning beside each squad that is older than the last squad building update (which might also change available slots in general). We could also give user access to the description field, so they can put arbitrary notes there when storing a squad?

**Comment by cm5089** [comment]
I say keep it in the selection - it's useful when list building and it means not having to select or mouse over each entry.  Alternatively have a Initiative graphic on the summary and remove it from the selected text?

**Comment by Patschke** [comment]
@cm5089 the setting is now available, (the dropdown beside the print/load/random bar) but is not beeing saved until the PR to the backend is accepted, too. As soon as that one is merged as well, yasb is able to remember your settings.
