### ISSUE TITLE
Collection missing

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#279]
## YASB 2.0 Bug Report

I'm logged in, I can load saved lists.  I do not have a 'your collection' button, nor am I getting 'you own x' info in the mouseover panel.

### Language

English.

**Comment by Patschke** [comment]
What Auth Provider are you using? What Browser are you using? Have you tried using another computer to log into you account, to tell whether the issue is related to a bug that caused your account data to be corrupted, or an issue with your system set up? Are you seeing any errors in your logs (to open the log hit ctrl+shift+k in firefox, ctrl+shift+j in chrome)? 

Without further information I can currently just say, that everything works fine for me and I am not able to reproduce that bug - which makes it impossible to fix it...
