### ISSUE TITLE
XWS errors with hardpoints

### ISSUE THREAD

**Issue by raithos** [raithos/xwing#314]
Noting to myself that when XWS exports it includes hardpoints for t-70s and other ships, it should not include the hardpoint. As well, when importing a list, if the slot does not exist but the hardpoint upgrade does, to add it.

**Comment by Patschke** [comment]
There are some other things I wanted to change on the xws loading somewhen: 

I think it would be a good idea to just create a serialized version of the list from the xws input (#251). That serialized string would than be passed to the usual loadFromSerialized, so we need to implement stuff required for proper loading only once (e.g. loading a gunner that requires a rotate arc action might fail, if no turret has been loaded yet. Having all those loading stuff at one place would simplify proper loading). If we do that, we may as well want to allow the upgrades in the serialized strings to be ordered arbitrarily (as the strict order with -1 for empty slots will cause issues if FFG keeps adding/removing slots from ships with the point updates). 

If one tries to load a xws squad from another faction, we should simply switch over to that faction instead of failing the loading attempt. 

I'd also allow loading xws data via url, so I could create a PR for ListFortress to have a "load in yasb" button next to the edit button of the lists. That should be relatively straightforward to do. If I see a list in ListFortress that I may want to play with a few modifications, it would be quite nice to be able to just open it in yasb.

**Comment by raithos** [comment]
Exports are fixed.... but imports dont have any checks for hardpoints. more problems I guess

The serialized loading does sound good and we should do that.... eventually.

im pretty sure there is already a xws to yasb converter out there so listfortress would just have to add that in as a part of it.

**Comment by Patschke** [comment]
> 
> 
> Exports are fixed.... but imports dont have any checks for hardpoints. more problems I guess
 
Well, we need to either select the proper hardpoint as soon as a missile/torp/cannon is about to be added (and the ship does not have the specific slot), or rework hardpoints in a way, that allows missiles/torps/cannons to be put into the hardpoint slot directly. The later would have the benefit, that it is much easier to decide what I want to pick as hardpoint, if I can see the whole list of all available stuff from the drop down (so I can e.g. compare and change between HLC, Protontorps and Prockets more easily). 

> 
> The serialized loading does sound good and we should do that.... eventually.

If we need to rework something on the loading methods now, we can unify them now as well? As slots may be added/removed from ships, we should not rely on the order in our own serialization. So it would be usefull, to find the proper slot for each upgrade when loading from serialized input (which needs to be done for xws always). 

> 
> im pretty sure there is already a xws to yasb converter out there so listfortress would just have to add that in as a part of it.

I am not aware of one, but you may still be right about that.

**Comment by zacharyp** [comment]
BTW, I added a "reverse" POST XWS to YASB url endpoint in yasb2-xws: https://github.com/zacharyp/yasb-xws#reverse-xws-to-yasb

**Comment by Patschke** [comment]
Ah, well. I wondered if you were actually writing a parser to do so. Turns out it's basically just a headless browser that will click the import xws button, right?

**Comment by zacharyp** [comment]
Yeap, that's the way it used to be as well.  I used Google's puppeteer library to do the headless browser clicking.  If the YASB code was (heavily) refactor'ed to not be so tied to the UI interactions, then the XWS parsing code be done just using that code directly.

**Comment by Patschke** [comment]
Doing so was part of my todo list anyway. Is now done in #251 

Currently xws loading will use serialization version 7, while everything else is still at v6. We should change it to v7 as well for the next point update, as v7 does not care about upgrade orders. As FFG may add/remove slots from ships, it seems to be a good idea to be able to load squads with changed slots. 

I'll now have a look on how I want to handle hardpoints.

**Comment by Patschke** [comment]
I reworked the handling of hardpoints in https://github.com/Patschke/xwing/commit/be6205155a5b16ef9c9b4a3036c99d4d8de0c65b

I think this is a clean solution, and I like it. Probably one should test a bit if everything works and nothing got broken, but as far as I can tell everything is fine.

**Comment by raithos** [comment]
The change is pushed, I am going to test this a bit more before we close this, I think that if there aren't any issues with this, lets not bother waiting for a points change. We just need to let @zacharyp know when we do the change so he can update simultaniously.

**Comment by FirestormSquadronfirecast** [comment]
When loading the xws into TTT the hardpoint does not appear on the overlay for any of the hardpoints.

**Comment by Patschke** [comment]
I'll have a look at this. It seems like we export the hardpoints as part of a hardpoint slot, which does not exist. Instead we should export it as a torpedo/missile/cannon depending on the selected card.

**Comment by Patschke** [comment]
I pushed a possible fix in c777409fb6de8d2212d47b31d7a89e81c928f455 as part of #371

**Comment by Patschke** [comment]
Can somebody confirm, that the xws now works with TTT? I don't use TTT, so I could not test it myself, but I believe this issue can be closed.

**Comment by Patschke** [comment]
So... I believe this issue can be closed by now?
