### ISSUE TITLE
Clone pilot fails for gunboat with os-1 config and barrage rockets 

### ISSUE THREAD

**Issue by atree23** [raithos/xwing#373]
When a generic Alpha Class Starwing (Gunboat) has the OS-1 Arsenal Loadout and Barrage Rockets equipped using the copy ship ability does not cause the Barrage Rocket missile upgrade to be copied to the new instance of the ship. This only appears to be impacting ships that require an upgrade to add the required second missile slot for Barrage Rockets. Since the new Diamond-Boron missile is unique, this is a non-issue for the recently announced double missile upgrade.

Steps to Reproduce:
1. Under Empire add Alpha Class Starwing to list (either Rho or Nu Squadron Pilot)
2. Add OS-1 Arsenal Loadout configuration upgrade to the Alpha Class Starwing
3. Add Barrage Rockets missile upgrade to the Alpha Class Starwing
4. Select Clone Pilot button

Expected Results:
The Alpha Class Starwing ship is cloned and a new Alpha Class Starwing with both OS-1 Arsenal Loadout configuration and Barrage Rocket missile upgrades appears in the list. Both instances of the Alpha Class Starwing are identical.

Actual Result
The Alpha Class Starwing ship is cloned and a new Alpha Class Starwing with the OS-1 Arsenal Loadout configuration upgrade but without the Barrage Rocket missile upgrade appears in the list. The original Alpha Class Starwing still remains with both the OS-1 Arsenal Loadout configuration and Barrage Rocket missile upgrades.

Language: English

**Comment by Patschke** [comment]
Thanks for the note, I am able to reproduce the bug you described and I do consider it a bug. 

As a work around you may simply put the Barrage Rockets in the 2nd missile slot, and everything will work fine. 

The issue basically is, that upgrades are added one after another during the copy, so by the time the copy procedure tries to add Barrage Rockets, they cannot be added since they require a 2nd missile slot. I will have a look in how to fix it later.

**Comment by raithos** [comment]
Will push this change once I have a chance to review it a bit more. likely tomorrow itll go up

**Comment by atree23** [comment]
Running through the repro steps the issue looks to be resolved. Thanks for
taking the time to look into the issue.

-Joel
