### ISSUE TITLE
Points in overview

### ISSUE THREAD

**Issue by Morplingmartin** [raithos/xwing#409]
Thanks for your great efforts in making this site. Just trying to help to get it even better

### Expected Behavior
I expect the overview list to hold the points of the list

### Actual Behavior
The list overview has the old points.

### Language
Engelish

**Comment by Patschke** [comment]
A list needs to be opened and saved again, in order to update the points (which will fix stuff like wrong slots as well). There is a "reload all" button in the list overview, which will do exactly that for every list. As reloading all lists may take a while (especially if you have a lot of lists) and people may archive their lists on point changes instead of reloading them, I am not going to do that automatically without notice. 

I hope this helped you. If you have any further questions, feel free to ask.

**Comment by Morplingmartin** [comment]
Cool. Thanks for the information

Greetings martin

Outlook voor Android downloaden<https://aka.ms/ghei36>



Van: Patrick Mischke
Verstuurd: woensdag 17 juli 13:49
Onderwerp: Re: [raithos/xwing] Points in overview (#409)
Aan: raithos/xwing
Cc: Morplingmartin, Author


A list needs to be opened and saved again, in order to update the points (which will fix stuff like wrong slots as well). There is a "reload all" button in the list overview, which will do exactly that for every list. As reloading all lists may take a while (especially if you have a lot of lists) and people may archive their lists on point changes instead of reloading them, I am not going to do that automatically without notice.
I hope this helped you. If you have any further questions, feel free to ask.
