### ISSUE TITLE
Possible to move the Format dropdown?

### ISSUE THREAD

**Issue by wilder3jw** [raithos/xwing#412]
### Expected Behavior

Currently, whether Hyperspace or Extended comes up for a new lists seems all but random.

### Actual Behavior

I am constantly building a Hyperspace legal list, but forgetting to chage the dropdown to Hyperspace.  When I do change it, my list is wiped out.

It would be great if the Format dropdown could be moved left, as more of a noticeable reminder to select the desired format.

### Language

English

**Comment by Patschke** [comment]
What we should really do is just deleting not hyperspace legal stuff if one changes the game mode, instead of doing a reset...

**Comment by raithos** [comment]
Yes, that is the proper solution @Patschke...

**Comment by Patschke** [comment]
Should be done properly in 6105572947b487bb1e6881d74d0176392cb20c0d

I've basically added a hyperspace legality check to the validation function, and calling that instead of doing a squad reset on change from extended to hyperspace. Works fine according to my testing. 

So after that goes live, you can simply change between Extended and Hyperspace at any time - it will only remove those ships and upgrades, that are not allowed in Hyperspace.

**Comment by raithos** [comment]
Its live!
