### ISSUE TITLE
Multiple-slot upgrades can't be easily swapped

### ISSUE THREAD

**Issue by HumbleBob** [raithos/xwing#457]
## YASB 2.0 Bug Report

For ships with multiples of the same upgrade slot, users should be able to swap freely between upgrades that take up the same number of slots, e.g. Diamond-Boron Missiles -> Barrage Rockets or Emperor Palpatine -> Death Troopers.

### Expected Behavior

Whether or not a multiple slot upgrade can be taken by a ship should be determined as though the slot being modified were empty; e.g. when modifying a crew slot containing Emperor Palpatine, the second crew slot that Palpatine takes up should count as empty when evaluating the ship's available crew slots.

### Actual Behavior

Upgrades that take up multiple slots are grayed-out when swapping out an upgrade that takes up the same number of slots if the second slot taken up by the upgrade being swapped prevents there being enough space for the new upgrade.

### Language

N/A.

**Comment by raithos** [comment]
This is basically not fixable due to how we determine the upgrade requirements. There is as of right now no way to determine why an upgrade slot is disabled, and as such no way to discern if those slots would become available with which upgrade is applied. Honestly there's no drive on my part to try and rework this since the edge case is pretty minor and addressable by simply removing the upgrade before picking a new one.

**Comment by raithos** [comment]
I'm going to close this for now since it's not something I have any intent to solve since it requires quite a bit of reworking for a very small benefit. However, if there is a rework of how we do upgrade requirements, I'll keep this in mind.
