### ISSUE TITLE
R4 Astromech makes E-Wing Hard-1 maneuvers on chart have odd colors

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#459]
Here's what it looks like when you add R4:
![image](https://user-images.githubusercontent.com/10382630/68519204-73ad7280-0244-11ea-9dcd-b713787219d3.png)

The red maneuvers turn into..... blueish-white?

(very critical issue, of course)

**Comment by Patschke** [comment]
What color scheme would you suggest for a maneuver that has been modified? Maybe we should use a green border? The blue style might be a leftover from 1.0 where maneuvers were red, white or green - and blue some neutral color.

**Comment by XPav** [comment]
It’s only the EWing which looks weird, because it’s the only one that has maneuvers that go Red to White.  All the White to Blue moves look fine, and it’s totally fine.

**Comment by raithos** [comment]
This is actually working as intended, the border is supposed to be a different color to indicate that the maneuver has been modified. However, sometimes this wouldn't work for blue maneuvers which is why you may not have noticed it. I will change the outline color to be more neutral as to not cause confusion.
