### ISSUE TITLE
1-ship Randomizer for Aces High

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#476]
With Aces High being all the rage, wouldn't it be fun to have a single-ship randomizer?

**Comment by raithos** [comment]
I'm hesitant to add more options to the randomizer, a) because the randomizer algorithm is already kind of janky and prone to breaking (we never designed it, we just kind of fixed it), and b) it would become very cumbersome to support a lot of alternative formats and add unnecessary overhead to the site.

Also right now you can just set the point limit to 80, and randomize until you get a 1 ship build, so you could do the aces high format just fine without needing extra code
