### ISSUE TITLE
Request: Hyperspace Legal Filtering

### ISSUE THREAD

**Issue by Will-Maiden** [raithos/xwing#503]
I really love how if components aren't legal (i.e. Upgrade needs a red barrel roll, but ship doesn't have it) then the upgrade is listed but it is faded out.

This kind of feature is so much nicer in helping me identify the issues in my list, rather than removing options because of some setting I might not have clocked.

It would great to have a similar feature for filtering Hyperspace legal content.

A Tickbox that, when true, checks if the pilot or upgrade is Hyperspace Legal and will display it as greyed-out/unselectable, ideally in a different colour to what is illegal due to standard deckbuilding prerequisites.

**Comment by Patschke** [comment]
I guess you noticed yourself, but just for anybody stumbling across this side: There is a drop down that allows you to select hyperspace as game mode. It will actually not grey out non-hyperspace stuff, but remove it entirely. 

If this request actually is about adding an option to only gray out stuff instead of hiding it completely, I'll remember this, but will only implement it if that request emerges more than once.

**Comment by Will-Maiden** [comment]
Yeah, I noticed the dropdown just after posting.

Being able to see  what is not available is still useful, though, but it's fair to only implement if similar requests come though.

Thanks.
