### ISSUE TITLE
Allow adding conversion kits to your collection

### ISSUE THREAD

**Issue by mwhuss** [raithos/xwing#504]
I started my collection by buying used 1.0 ships and then getting the conversion kits. It's be great if could add a conversion kit to my collection and all the pilots/upgrades would get added automatically.

**Comment by Patschke** [comment]
Well... you sureley can. The conversion kits are listed in the expansions tab of the collection. You need to add all 1.0 ships as individual ship-only items, because owning a conversion kit does usually not mean to own that exact number of ships - so the kits include all the pilots/upgrades, but no ships on their own. 

If I missunderstood your question, please clarify it - and I'll try to help.

**Comment by mwhuss** [comment]
Ah, I missed them in the list. That's exactly what I wanted, thanks!
