### ISSUE TITLE
"Load Squad" function

### ISSUE THREAD

**Issue by MatBe14** [raithos/xwing#514]
### Expected Behavior

Displaying the list of my saved squads.

### Actual Behavior

For both the Resistance and Galactic Republic factions, I only see the "Fetching squads..." logo, circling, and no lists are displayed.

For the five other factions, it works as normal (instantly).

### Language

English

**Comment by MatBe14** [comment]
Update: It's now the same for Rebels, Scum Resistance and Republic... all factions for which I recently saved Hyperspace lists. Not sure if that's a factor but it seems to be the common denominator for me. Also, the problem started yesterday (Jan. 22nd) after I saved new Hyperspace lists for Resistance and Republic.

**Comment by raithos** [comment]
OK, so big update, right now the saves are broken, it has something to do with some cookie things that Geordan and I were working on because of some chrome related stuff. I have put in a hotfix to fix the issues of being able to see your old lists, however, until I fix the main issue which is that saves are not going through properly, you will not be able to save files. I'll update here when i have more info

**Comment by raithos** [comment]
Ok, got things resolved, you should be able to save lists again. Also, any lists that were saved during the last 24 hours are lost unfortunately, sorry about the inconvenience.
