### ISSUE TITLE
Support for multiple collections

### ISSUE THREAD

**Issue by michaelrstewart1** [raithos/xwing#528]
## YASB 2.0 Feature Request
It would be nice to have the option to manage multiple collections. There are a lot of use-case scenarios where this would come in handy, such as using pooled inventory when playing in groups, etc.

Thanks!
### Expected Behavior

Be able to toggle between different collections, and assign squads to those collections.

### Actual Behavior

Currently no support for multiple collections

### Language

N/A

**Comment by raithos** [comment]
I've looked into this in multiple ways, and basically came to the conclusion that we'd have to completely re-write the backend system for YASB to make this work, and I'm just not willing to do that especially since it would impact the original YASB as well. The workaround for you is to log in via different accounts, theres 4 different ways to log in now, you use use a different account for each collection.
