### ISSUE TITLE
QuickBuild issue for RZ-2 A-WING RESISTANCE

### ISSUE THREAD

**Issue by EGNMX5** [raithos/xwing#554]
## YASB 2.0 Bug Report

First of all, thanks a lot for that powerful and lovely tool !

### Expected Behavior

Showing the full list of quickbuild pilots for RZ-2 A-WING

### Actual Behavior

Quickbuild for RZ-2 A-WING is showing only the first Pilot and Searching...

![image](https://user-images.githubusercontent.com/63339804/78760555-a2f61600-7981-11ea-8264-e2ba87c0f2d5.png)

### Language

French

PS : I found as well lots of texts, descriptions or titles not translated in french, Do you want I give you the translations ?

**Comment by Patschke** [comment]
Thanks for reporting the bug, will be fixed with PR #551 

Regarding translations: I do have a script that will do most of it automatically (parsing card texts), so I'll run that and see what it gives me. 
If you want to contribute in keeping the french translations up to date (running that script and performing the manual clean up, and I guess there is also quite a bit UI that would need translation...?), you are welcome to help. However, there is unfortunately no nice interface for "giving us the translations". As I see that you joined github an hour ago, I can offer you help for where to find the translations in the source code of YASB and how to contribute using pull requests - but be aware that it might take a while to familiarize with how source code works ;-)

**Comment by Patschke** [comment]
![grafik](https://user-images.githubusercontent.com/17853362/78768919-e4d88980-798c-11ea-973b-37a29c2cba32.png)

Most card translations are now part of PR #551 as well. They should match the official available sourcdes. As I don't speek any french I am unable to check if they are actually correct - the german translations usually contains quite a few mistakes...

**Comment by EGNMX5** [comment]
Works perfectly, even translations, thanks !
