### ISSUE TITLE
Tanslation helper seems incomplete 

### ISSUE THREAD

**Issue by blueAngel35** [raithos/xwing#578]
Hello
I was looking for help you to translate some contents in French following your read me in translation helper.

First the python script is unable to read known_typos.json because of unknown signs, in local I have to delete all content inside : "de" : [ ] 

Then I could use all scripts but every content is translated by the script but some contents are not in the content to translate for example : imperial raider and gozanti ships, all hard points upgrade and cargo upgrades

thank you for your project

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** If you can't log in, try updating your browser to the latest version, and if you're not using Chrome or Firefox, try them. There was a change to how cookies are stored and we updated to be in line with that but that breaks compatibility with some older browsers.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
For me the scripts seem to run fine. As this is the first time you run the translation scripts, the old translation file will not yet exists, as i decided to make them not part of the git repo. But everything should still run fine:

```PS B:\Programme\yasb\translation_helper> python .\jsonDownloader.py fr
Processing language: fr...
Downloading file from https://squadbuilder.fantasyflightgames.com/api/cards/...
Processing JSON file...
Wrote to api_export_fr.json.
PS B:\Programme\yasb\translation_helper> rm .\translation-fr.old.coffee
PS B:\Programme\yasb\translation_helper> mv .\translation-fr.coffee translation-fr.old.coffee
PS B:\Programme\yasb\translation_helper> python translate.py -l fr
Please edit the following cards manually:
L3-37's programming: Merge into L3-37
Found pilot name multiple times: •Bossk
•C-3PO: Found upgrade name multiple times:
Chewbacca : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Grappling Struts : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Han Solo : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Integrated S-foils : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Landing Struts : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Pivot Wing : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Servomotor S-foils : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
Stabilized S-foils : Probably double-sided. YASB wants you to merge double-sided-cards together into one.
“Chopper” : Probably double-sided. YASB wants you to merge double-sided-cards together into one.```

The fix-me stuff might be a little bit outdated (it was supposed to help translators for different languages, as some common manual fixes are required, but as I was the only one maintaining all translations I got sloppy with updating it), but in principle everything should still be ok. Can you give me some more specific log output where it breaks for you?

I grab the translations from the FFG api for the squadbuilder: https://squadbuilder.fantasyflightgames.com/api/cards - as their squadbuilder does not seem to include epic, I can't grab the epic cards/upgrades. If you are aware of a up-to-date source I could automatically parse, I might consider including that as well. For now, you'll have to manually type in the translations for those cards. 

It's great to see somebody joining in for some translation work, especially since I do not speak any french myself ;-) If you can provide a more detailed bug-report, I'd be happy to help you!

**Comment by raithos** [comment]
@blueAngel35 do you have everything you need from @Patschke? It looks like everything is addressed but I want to be sure
