### ISSUE TITLE
Hotshots n Aces Quickbuilds

### ISSUE THREAD

**Issue by KesterSmith** [raithos/xwing#580]
Can we get the Quickbuilds for Hotshots and Aces added? I'm happy to help write things up if needed. We are planning a mini tourney using them and it would be very handy

**Comment by KesterSmith** [comment]
Can we get the Quickbuilds for Hotshots and Aces added? I'm happy to help write things up if needed. We are planning a mini tourney using them and it would be very handy

**Comment by Patschke** [comment]
Hi @KesterSmith, 

since FFG stopped updating their quickbuild pdfs I've become lazy updating the quickbuilds. If you want to help out, you are welcome to do so. Here is how you can get started: 

I've granted you access to https://github.com/Patschke/xwing/edit/master/coffeescripts/cards-common.coffee. The quickbuild data ends currently at line 16698, you can "simply" add the missing quickbuilds using the same scheme as the quickbuilds above (scroll a bit up to find some quickbuilds that are not wingmate-quickbuilds). The id simply counts up, all other fields should be rather self-explaining. The formatting (aka number and type of whitespaces) is important, so be sure to keep that style. Don't worry, you can't break anything - this is not changing the live version of YASB directly, but rather a working/testing copy. I'll test your changes first, so you don't have to be afraid of breaking anything. Also git is able to undo every change if need be. 

If you are familiar with git you may of course also fork the repo and commit a PR - if that sentence did not make any sense for you, just use the method above ;-)

If you have any further questions don't hesitate to ask - as someone who has been working with git (and YASB) for years, stuff that seems obvious to me might be actually confusing to anyone who want's to get started. I'm happy to help you if that's case.

**Comment by KesterSmith** [comment]
None of the git stuff made sense but the first part makes sense and I am happy to have a look and see what I can do, thanks!

**Comment by KesterSmith** [comment]
Oops I closed it, I suppose that's fine

**Comment by KesterSmith** [comment]
Ok, I've updated that file. Let me know how well I did!

**Comment by Patschke** [comment]
A few minor typos (cefef5978a16b82dde3e95325bd4905c798e76ef), but all in all it looks good. Thanks for the work, will be live with the next update!
![grafik](https://user-images.githubusercontent.com/17853362/84188041-3c7d9900-aa93-11ea-8192-698460361ce4.png)

**Comment by SneakyGitau** [comment]
I'd be happy to give it a go if you point me in the right direction
