### ISSUE TITLE
Enhancement Request - Export Collection

### ISSUE THREAD

**Issue by CaryF300** [raithos/xwing#585]
This is NOT a bug report, but instead a request for new functionality.

Would it be possible to export a user's full collection in a CSV or XML format? If possible, it would be nice to include the faction for pilots and ships.

**Comment by Patschke** [comment]
This should be doable, yes. May I ask you, what the purpose of such an export would be? E.g. is there any application you want to use this data regulary for, or expect a lot of users to use this data? I am asking this for mainly two reasons: 
  * If there is an existing application that wants csv formatted x-wing collections, you should probably be more specific about the format - otherwise the data format will probably not match. 
  * If you just want an one-time export of your collection, it is much faster if you do it as follows, instead of me writing code to do so:

1. : Open your collection and just copy the content of the inventory tab: 
![grafik](https://user-images.githubusercontent.com/17853362/84706460-40129380-af5d-11ea-844d-a88d789cd83f.png)
2.: Paste it into your choice of text editor. Search and replace " - " with ";" (without the " but including the whitespace). The simplest one I could imagine was notepad, which probably exists for decades now and got never updated - but it still does the job. Save as collection.csv
![grafik](https://user-images.githubusercontent.com/17853362/84706693-b911eb00-af5d-11ea-8228-c7adaff1e1ec.png)
3.: Import it in your choice of software reading csv files. Choose ; as separator. You should have a decend version of your collection (of course, without factions). 
![grafik](https://user-images.githubusercontent.com/17853362/84706954-26258080-af5e-11ea-88fc-dee987652731.png)

If you can describe a case where I can see a need for a dedicated export as csv function, I might consider doing so. 

Thanks for your feedback to YASB, every idea on how to improve it further is always welcome!

**Comment by CaryF300** [comment]
This isn't for an existing application, but more for me to work with in Excel, or Access. I'm trying to find a way to better inventory my collection. Between my brother and I we have in the neighborhood of 200 ships. One thing that is missing from that list is the faction.

Have a great day,
Cary Fleming
Laser Wonders
UPIC: LsrWnds
Toll-free 833-452-7966

----------------------------------------

**Comment by raithos** [comment]
The collections will not sort by faction as that's not how we organize our backend, it's unlikely that we'll implement a feature that supports it without also adding factions to every expansion pack in the game.

**Comment by CaryF300** [comment]
No need to sort anything. Just having the faction listed next to the ships would be a help. As a programmer myself, I totally understand if this is something that you decide not to do.

Have a great day,
Cary Fleming
Laser Wonders
UPIC: LsrWnds
Toll-free 833-452-7966

----------------------------------------

**Comment by raithos** [comment]
Yeah, it's not something we're going to do. Hopefully the suggestions provided is enough for you. Also in case you would prefer the raw json, if you're logged in you can go to https://yasb-backend.herokuapp.com/collection and get your collection data directly.

**Comment by CaryF300** [comment]
Thank you. That is useful.

Have a great day,
Cary Fleming
Laser Wonders
UPIC: LsrWnds
Toll-free 833-452-7966

----------------------------------------
