### ISSUE TITLE
BBCode and HTML output are broken

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#592]
They are both currently blank.

**Comment by Patschke** [comment]
They are working fine for me. Unless you can provide at least some of the information we request on submitting a bug, there is not much I can do for you here: As long as I can't see a bug, I can't figure out what the issue is and how to fix it. So please include information, how someone can reproduce this, e.g. which browser are you using, are only specific squads, factions or languages affected, are you logged in or not, etc.

**Comment by raithos** [comment]
without more info we can't do anything to fix it as we cannot replicate the issue. I will reopen if more info is provided
