### ISSUE TITLE
Rebel C3-PO

### ISSUE THREAD

**Issue by Brachinus** [raithos/xwing#600]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

**The C3-PO of the Rebel Faction is the C3-PO of "Galaktische Republik" (don't know how its called in englisch).**

### Language

The affected language(s).

**Comment by raithos** [comment]
@Patschke

**Comment by Patschke** [comment]
Yep, vielen Dank für den Hinweis. Im deutschen Sprachpaket war zweimal eine Übersetzung für den Rebel-C-3PO eingetragen, wovon die zweite eigentlich zur Republik gehört hätte. Entsprechend ist bei den Rebellen der falsche Text, und bei der Republik der englische Text aufgetaucht. 

Just a wrong name in the translation file, will be fixed with PR #602
