### ISSUE TITLE
Increase Ships shown at Drop-down menu

### ISSUE THREAD

**Issue by Takko550** [raithos/xwing#603]
### Normal Behavior

Only 5 ships/ are shown when you press the Ship Chassis Selection, compared to 7 for other Drop-down menus

### Feature Request

**Please increase the number of ships shown,** like the other Menus, e.g. Pilot, Upgrades etc.

Folks who set their mouse middle scroll to scroll more than 5 lines will miss some ships as they scroll through the list. Quite annoying and have to manually click through. This makes it having to slow down list building when the Chassis list is long.

### Language

English

**Comment by Patschke** [comment]
Currently both drop downs have the same size (e.g. 200px). However, the Ship Chassis selection shows less items, since the ship icons are displayed at a size of 1.5 lines, causing the entries to be spaced further apart. I don't think that we should make them have different sizes, as they should always have a reasonable size rather than a fixed number of entries. We could either make both larger, or have the ship icons become smaller: 

Current:
![Bildschirmfoto von 2020-07-30 15-04-31](https://user-images.githubusercontent.com/17853362/88927210-62dfd980-d277-11ea-9d2e-5bbd576fa3b9.png)

Resized Icons:
![Bildschirmfoto von 2020-07-30 15-05-34](https://user-images.githubusercontent.com/17853362/88927212-63787000-d277-11ea-99b6-8de22cdca063.png)

Larger Menu:
![Bildschirmfoto von 2020-07-30 15-04-17](https://user-images.githubusercontent.com/17853362/88927207-62474300-d277-11ea-951c-ad6568bb6ef0.png)

**Comment by Takko550** [comment]
Hi,

Wow good point!

 I like having the menus both be larger, would show the ship silhouettes
and show more choices.

What do you think?

**Comment by raithos** [comment]
I added css to increase the menu size, its not quite 7 but its moderately larger. We can adjust if its a problem in the future
