### ISSUE TITLE
Very Slow to Load Since New Points!

### ISSUE THREAD

**Issue by RebelJP** [raithos/xwing#608]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Squads load in under 1 minute, even after hard refreshes.

### Actual Behavior

Squads are taking over a minute to load since the new points.

**Comment by Patschke** [comment]
For me a squad loads within <3 seconds (several ships with a dozend upgrades). Of course, the amount of data is so small, that further optimization would be possible, but that seems fine to me. 

Unless you can give me enough information on your settings that I am able to reproduce the slow loading, I can't fix it.

**Comment by RebelJP** [comment]
Thanks for the quick response. I wasn't sure if it was just me or others
were experiencing the same issue. Glad to hear it's not the program. I'll
look into other possibilities!

Take care,

Jonah Piscani

**Comment by Patschke** [comment]
I didn't mean to say that it is not the program - maybe it is actually slow in some configuration. E.g. a specific combination of browser and operating system. Or maybe a collection with a large number of indiviual items, combined with whatever, or ... All I said is: As long as the description you can give for the issue is not specific enough that I can follow it "step by step" to get the same result (i.e. loading a squad taking some minutes, which is clearly not what it should take), it is hard to tell what the reason is and if there is anything we can do to improve it.

**Comment by raithos** [comment]
Since we have no way to test or fix this atm, I'll wait to see if theres a way to reproduce it. If there is please respond and I'll reopen.

**Comment by RebelJP** [comment]
No worries - I cleared my cache and everything is now loading fine! Thanks
so much for your help and your dedication to the X-wing community!
