### ISSUE TITLE
Calibrated laser upgrade card

### ISSUE THREAD

**Issue by grim0126** [raithos/xwing#626]
When choosing this upgrade card it does not give you preview text on the Delta - 7 
<img width="1385" alt="Screen Shot 2020-09-14 at 5 37 49 PM" src="https://user-images.githubusercontent.com/71295595/93145062-1cbcc900-f6b1-11ea-8b84-e7963ed3e753.png">

**Comment by Patschke** [comment]
There is no preview given, since the text field does only contain flavor text (and we don't show that in YASB by default). 

[<img src="https://static.wikia.nocookie.net/xwing-miniatures-second-edition/images/4/46/Swz_delta-7b.png/revision/latest/scale-to-width-down/350?cb=20190217060125">](https://static.wikia.nocookie.net/xwing-miniatures-second-edition/images/4/46/Swz_delta-7b.png/revision/latest/scale-to-width-down/350?cb=20190217060125)

However, I agree that we should show stat changes from cards in the card view.

**Comment by raithos** [comment]
Yeah I'll add it later today
