### ISSUE TITLE
Wrong ship count

### ISSUE THREAD

**Issue by pooleman** [raithos/xwing#67]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** If you find your collection has extra ships, this is expected. In order to allow loose ships I have added ships for each kit based on what the kit can convert. This has to be done right now otherwise you would not be able to add loose ships. Until I have time to overhaul the collection system, or all the existing ships are released in their own blister packs, this is the only way to allow loose ships being added.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by pooleman** [comment]
Expected Behavior

Collection shows ship count based on what is in the conversion kits. 

Actual Behavior

Even in the “new squad” page with no ships added all of my ships are in red, as though I’ve already added the maximum amount of ships available, even though I’ve added nothing. I have completely emptied my collection and them re-entered my collection (all second edition stuff, just the core, rebel conversion kit, saws renegades, and y-wing).

**Comment by raithos** [comment]
Conversion kits are now separated from your ship collection. and no longer add ships. This was requested by several people in order to more accurately represent their collections. 

To fix the red issue, if you go into your collection and click on the ships tab, there is a list of all available ships and you can update the numbers accurately of all the 1.0 ships you had prior to the 2.0 launch. I am currently working on a setting to disable collection checking if but it wont be out until later.
