### ISSUE TITLE
Show upgrade restrictions

### ISSUE THREAD

**Issue by boppin-along** [raithos/xwing#670]
It would be nice to have the restrictions on upgrades shown in the upgrade card text.  Having it colour coded to indicate which restrictions haven't been met (when mousing-over items in the drop-down list) would also be useful.

**Comment by raithos** [comment]
That doesnt seem practical given the number of different possible restrictions there are. However, I need to get better at listing the restrictions in the card itself for all cards. So that will be an ongoing process

**Comment by boppin-along** [comment]
Hmmm, I should have been more clear with what I meant by the colour coding idea, sorry about that.

What I was intending was colour coding the restriction keywords on the card text view.

eg. Precision Ion Engine would list "Requirements: TIE, Agility 3".  A TIE Striker looking at that card would show "TIE" in regular text, but "Agility 3" in red text, as it doesn't meet that requirement.

Is that feasible?

**Comment by Patschke** [comment]
We could consider some kind of solution, where the restriction_funcs itself generate some sort of text output, which is displayed together with the regular text. Of course, that would require rewriting all the restriction_funcs of the upgrades. On the other hand it would be easier to guarantee, that no upgrade is skipped (as it is not two different files).

**Comment by raithos** [comment]
The color thing still seems like more work than its worth, when just making sure we output the restrictions so people actually will always know what the restrictions are. I agree with @Patschke that codifying the restriction_funcs is the best solution. I am probably going to rewrite how restriction_func works so that instead of writing custom code every time, we make a new edge case and just return the type and values and let that run as a single function that controls all the restrictions.

**Comment by raithos** [comment]
restrictions are now listed for all upgrades with them automatically

**Comment by boppin-along** [comment]
Excellent! Thank you very much for that.
