### ISSUE TITLE
Force upgrade for Kanan Jarrus

### ISSUE THREAD

**Issue by Lybo24** [raithos/xwing#696]
Trying to select "patience" as the force upgrade for VCX-100 pilot Kanan Jarrus and it is greyed out

**Comment by Patschke** [comment]
This is (somewhat) working as intended. In the official points pdf (https://images-cdn.fantasyflightgames.com/filer_public/37/9b/379b83ca-2bd0-49c0-ab45-1ddc35b79f72/rebel_alliance.pdf) Kanan Jarrus only has the "Spectre" trait, he is not a "Light Side" Pilot (unlike e.g. Luke in the T-65 who has the "X-Wing" and "Light Side" traits). Therefore Kanan should not be allowed to equip patience, since this is restricted to "Light Side". 

I agree tough, that Kanan feels very light sided...
