### ISSUE TITLE
Upgrade cards from 1.0 appear in the inventory

### ISSUE THREAD

**Issue by marcne** [raithos/xwing#70]
Hi,

The upgrade cards I added to the 1.0 not being part of a expansion (i.e. a Push the limits bought separately) appear in the inventory.

Thanks for the platform. Is great. 

Best,
Marc

**Comment by raithos** [comment]
Hi, can you confirm you are on the 2.0 YASB, and also take a screenshot? cards like Push the Limit should NOT be showing up at all, it shouldn't be possible.

**Comment by LordVorKon** [comment]
What I'm seeing is that PTL does not, but Predator and C-3PO do appear both in the collection editor and in the 'you have x' line in the list builder.  (Same name, so that makes some amount of sense.)

Also in the inventory part of 'Your Collection' yeah, I'm seeing PTL also.

![image](https://user-images.githubusercontent.com/42716764/45641535-043e5780-ba73-11e8-9b7b-1113e3dc756f.png)

**Comment by raithos** [comment]
Ugh... can you guys like... ignore it? sigh FINE into the hole i go

**Comment by LordVorKon** [comment]
Well... yeah, we probably CAN....  :)

**Comment by raithos** [comment]
OK, here's the compromise. I can remove the items from 1.0 from the list, which I have pushed live. I cant do anything about the upgrades that have the same name, its just a downside of sharing the login information. Please update your loose upgrades and pilots accordingly to 2.0. Sorry

**Comment by marcne** [comment]
The ones which appear in 2.0 can be adjusted in the list so no big deal. If the 1.0 which are no longer part of X-Wing are removed will work 😊
  

  
Thanks!!
  
  
  
 marcnavarro. +34 639 829 222     
  

  
  
>
