### ISSUE TITLE
Faction Name improvement

### ISSUE THREAD

**Issue by eblingus** [raithos/xwing#704]
IMO it would be helpful to put the name of the Faction next to the icon, for those of us that do not have all the faction icons memorized.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
Hi, sorry I have no intention on doing this, the reason we went to faction icons is that if all the names are listed instead of the icons it takes up too much space along the top, and also messes up things for mobile. If it helps, its always good guys then bad guys (and scum for original trilogy), and then original trilogy, sequel trilogy, prequel trilogy. 

The best i can offer is that I can name the faction so you know which one youre in below the tabs.

**Comment by zatho-ger** [comment]
What would you think about a pop-up faction name when you hover a symbol?

**Comment by raithos** [comment]
I added a hover over with the faction name. I haven't added any translation, if someone wants to take care of that later its not something im interested in tackling.
