### ISSUE TITLE
Delta 7B + Stealth Device

### ISSUE THREAD

**Issue by Salohza42** [raithos/xwing#783]
### Expected Behavior

When adding a Stealth Device to Delta 7B it costs 6pts for a 2 Agility ship.

### Actual Behavior

Stealth Device on Delta 7B costs 8pts for a 2 Agility ship.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Nope, working as intended. The Delta is still a 3 agility ship. 

Has been answered several times, starting #332 #363 #382 ... and the last time #776 (two weeks ago). Since I'm a nice person, here the ruling again: 
```

Q: If a ship equips an upgrade that alters one of its values (such as agility), how does this affect variable cost upgrades?

A: Other upgrades are ignored when calculating variable costs, and the base values of the ship are used. 
```

You may either find this in the [official rules reference](https://images-cdn.fantasyflightgames.com/filer_public/d4/14/d41434fe-79e8-4ed2-aa73-11ba2fb1208f/_swzrulesreference_v130_book_wq_12420.pdf) on page 30 (first question regarding "List Building") or in the "Rules" section of [YASB](https://raithos.github.io) (e.g. search for "costs" and click the List Building entry).

**Comment by raithos** [comment]
I swear that if we get this one more time im going to add it as a note on the submission form.
