### ISSUE TITLE
B-Wing Hera  Quick Build includes the wrong title

### ISSUE THREAD

**Issue by Simplician** [raithos/xwing#785]
### Expected Behavior

The Quick Build for Hera Syndulla in a B-Wing, should include the Epic version of "B6 Blade Wing Prototype". (crazy though, right?)

### Actual Behavior

Instead it loads the standard title.

### Language

-

**Comment by SpaceMarineCMDR** [comment]
Currently the epic version of the B-Wing prototype isnt even on here yet I don't think.

A-Wing Ahsoka is also only listed as 1 point in Quickbuild

**Comment by Patschke** [comment]
Nah, the epic version of the Prototype does exist (it's not a title but an Command upgrade, not sure if that's correct?). Will be fixed with #786 (which also includes some changes to the translation system, so it might take a few days until it's online). 

Thanks for the note on Ahsoka, going to fix that as well.

**Comment by Simplician** [comment]
The Epic Prototype has both the Command and Title icons. It's selectable in the Commands, but grays out the title when you select it, which seems correct.
