### ISSUE TITLE
Adding Multiple cards that cost different values based on ship types

### ISSUE THREAD

**Issue by eagletsi111** [raithos/xwing#83]
## YASB 2.0 Bug Report

How about adding multiples of cards that cost multiple values based on ship types, so for instance stealth device is based on the Agility of a ship,  Just add multiple cards and costs and list them by ship.    Then force the user to choose the correct one.          It' would be an easy fix and that stupid star is really bad, plus I've seen people with the wrong values and over costing, because they forget about the star.

Thanks,

**Comment by iwazaru** [comment]
It sure would be an improvement to see the exact cost before the card is selected. But wouldn't it be more user-friendly to show just one card, but instead of the star, the actual points cost based on the selected ship? The fact that the cost is variable and the cost for ships with a different agility would still be displayed in the card preview.

**Comment by raithos** [comment]
I'm not adding multiple cards, but I will update the value when selected so that people can know how much the card costs on the ship selected. This was intended from the start but I got caught up by other more pressing issues and no one else really complained about it. This update should go out soon.

**Comment by eagletsi111** [comment]
Ok.   Great.     I figured you might want to do that, but wanted to give you an easy way to get around it.

Thanks for all your hard work,   do you have a donation button?

**Comment by raithos** [comment]
No.... I have a paypal account but I never really thought about monetizing YASB since it only cost me time and effort.
