### ISSUE TITLE
General Hux crew on the Xi shuttle

### ISSUE THREAD

**Issue by RUNZZxwing** [raithos/xwing#861]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Hello ! A very "niche" thing I just noted : On the FO Xi shuttle, it shouldn't be possible to equip the crew "general Hux". The prerequisite is a white coordinate, and the native coordinate on the Xi is red. Unless i am missing something. Although It is possible to equip first the "tactical officer" crew to make the red coordinate white, and then equip Hux as a second crew.

### Actual Behavior

Right it is possible to directly equip the crew "general Hux" on the Xi shuttle. It shouldn't be possible.
### Language

The affected language(s).

**Comment by Patschke** [comment]
As far as I know it is not entirely clear if that should or shouldn't be possible. The Rules reference just states on page 22:
> Some upgrade cards have one or more of the following rules in their 
restrictions box:
> * [...]
> * If there is an action icon, this upgrade can be equipped only to a 
ship with that action on its action bar. This does not include actions on its 
linked action bar.

So to me it is not completely clear, if "that action" has to be the same color. The official squad builder allows to equip Hux as well, so I guess we'll keep it that way. Since he is completely pointless when not having a white coordinate available, it won't matter after all.

**Comment by raithos** [comment]
AMG has previously ruled that for prerequisites that if the icon does not specify a color, it works for any color. This is working as intended and correctly
