### ISSUE TITLE
the black box builder keeps everything French

### ISSUE THREAD

**Issue by NetterMizuno** [raithos/xwing#911]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior
Expecting after changing language to english everything would be english

### Actual Behavior

https://raithos.github.io/jt/?f=Galactic%20Empire&d=v8ZhZ200Z&sn=Unnamed%20Squadron&obs=

This thing keeps on being french for me, even if i try to change the language, refreshing, clearing chacke/cookies, trying other browsers/PC's/phone. It still keeps being french for me.

### Language

French and English
![yasb](https://user-images.githubusercontent.com/81223803/148873927-07baff04-9dd2-4b38-9aa7-0a1a1e72635b.png)

**Comment by Patschke** [comment]
Thanks for the report. I can confirm and reproduce this behaviour. 

I do not intend to fix this for the blackbox version just now. If it bothers you, please open a console (ctrl+shift+k in firefox or ctlr+shift+j in chrome) and enter: 
```javascript
exportObj.loadCards("English")
exportObj.translateUIElements()
```
to translate cards/UI to another language. I have no idea why the language selection is not working for this sub-version of YASB. Maybe I'll look into it on another day, but probably I won't. 

Sorry for any inconvenience that is caused by this bug.

**Comment by raithos** [comment]
oh not fixing anything for the black box builder i should have noticed that before
