### ISSUE TITLE
will it stay?

### ISSUE THREAD

**Issue by redmoose79** [raithos/xwing#927]
howdy, sorry this isnt a bug but is this version of yasb staying around for a while for those who wont be playing the new rules and points?   just wondering if i should print out 2.0 points now while i can still find them.

**Comment by Patschke** [comment]
Well, this is a git - so everybody can always go back to any point in time whenever he feels like it. This might however require compiling from source yourself, but in principle every version of YASB that existed at any time is still out here. Stuff like the backend may or may not work (aka you might be unable to login, save and load lists, or, similiar to what happens if you log in to YASB 1.0, you'd see your 2.5 lists as well, but can't load them in 2.0 YASB). Maybe we should add a tag "last 2.0 version" or something like that. 

I don't think that there is much reason to have yasb.app and the gh-pages running in parallel with the same version, so perhaps we'll just keep the 2.0 version in gh-pages? Maybe we'll add some /old pages? Who knows the future... However, I am not going to maintain a parallel 2.0 YASB - so there won't be new ships or bug fixes. Somebody else might of course want to do that, I can only speak for myself.

**Comment by raithos** [comment]
raithos.github.io still exists for all non 2.5 stuff
