### ISSUE TITLE
It would be GREAT to get a printable list of the point values for 2.0 before everything moves to 2.5 (really...3.0....let's be honest). 

### ISSUE THREAD

**Issue by PastorJman310** [raithos/xwing#930]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Not sure what you are asking for here. Old point pdfs are still out there: https://www.fantasyflightgames.com/en/products/x-wing-second-edition/ 

If that was not what you were asking for, please be more specific about what your issue is (and how it is related to YASB?). We're always happy to receive constructive feedback.

**Comment by raithos** [comment]
raithos.github.io still exists. were not supporting anything prior to latest though
