### ISSUE TITLE
Upgrades are incorrectly disabled when the loadout value would not exceed the ship's maximum

### ISSUE THREAD

**Issue by ToshioMagic** [raithos/xwing#932]
### Expected Behavior

Specific: I can swap from passive sensors to collision detector on echo. I can swap back from collision detector to passive sensors
Generic: If swapping upgrades in the same slot would keep the total ship loadout value below the ship's maximum loadout value, the option should be enabled.

It may be better to have all options enabled and just highlight the loadout value in red when it exceeds.

### Actual Behavior

When I try to swap out passive sensors for collision detector on echo, collision detector is disabled. I can remove the passive sensors upgrade and then switch to collision detector, so there is a workaround.

### Language

Only tested in English

**Comment by Patschke** [comment]
Yep, thanks for the note. I don't want people to accidentally build illegal lists, so just showing stuff in red is not what I think is usefull (especially since TOs would need to go through each individual ship rather than just checking that the total points is <=200). Therefore too expensive upgrades are still not select able. However, I the costs of the currently equipped upgrade should of course be ignored. 

Will be fixed with #928
