### ISSUE TITLE
TIE/wi Wisper

### ISSUE THREAD

**Issue by Rorix904** [raithos/xwing#944]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Says theres 2 tech spots.

### Actual Behavior

only lets me put on 1 tech upgrade

### Language

The affected language(s).

**Comment by Patschke** [comment]
Can't reproduce this one. 
![image](https://user-images.githubusercontent.com/17853362/155474467-55de81de-e341-4a3e-bd33-9640079386ee.png)
For me both Tech slots work just fine. Did you remove the Enhanced Jamming Suite? It's a free configuration upgrade (so usually people are meant to play it, which is why YASB equips it automatically), but it is occupying one of the two Tech slots as well.

**Comment by raithos** [comment]
working as intended, see @Patschke's comment
