### ISSUE TITLE
Recalculate points deleted all saved squads data

### ISSUE THREAD

**Issue by onifares** [raithos/xwing#971]
## YASB 2.0 Bug Report
I'm using YASB 2.0 for some time. I have plenty of squads saved, especially for SCUM. I want to thank you very much for all this great work, I sometimes have more fun experimenting with squad build with your app then playing the game itself.
Trying the new yasb.app, seemed great at start! After login with the same Google Account I use for the old YASB 2.0, I found many of my saved squad, thought it seemed you used some old backup. Trying to play around with the various functions of yasb.app, I tried "recalculate points" shown in the Load Squad menu.

### Expected Behavior

Squad would have maintained all ships and upgrades, showing updated cost, may showing the squad as illegal.

### Actual Behavior

All my squad data is gone. Now I see only a list of squads, all at 0 points, with no ships or upgrades.

### Language

Italian (I was using this language when I tried the "recalculate points"), now switching language doesn't seem to solve anything.

**Comment by raithos** [comment]
so a couple of things, all old squads are incompatible with the current version, thats by design due to the massive differences and changes in both how we calculate points and how much things cost. So when you recalculated your old lists, thats why it set it to 0. The main reason to have your old account is to save your collection which is unchanged by the new points. If you want to view  your old lists, they still exist on raithos.github.io

I would recommend deleting all lists (which you can do when u try to delete 1 list, an option for all comes up) as the old lists basically don't work and arent importable to the new version

**Comment by onifares** [comment]
Good morning.Thanks for your quick reply.If I delete all my list from the new yasb.app, they won't be deleted from the old raithos.github.io, right?How long will the old raithos.github.io will be up and running?
Thanks again.AS
    Il domenica 27 febbraio 2022, 23:28:17 CET, raith ***@***.***> ha scritto:  
 
 


so a couple of things, all old squads are incompatible with the current version, thats by design due to the massive differences and changes in both how we calculate points and how much things cost. So when you recalculated your old lists, thats why it set it to 0. The main reason to have your old account is to save your collection which is unchanged by the new points. If you want to view your old lists, they still exist on raithos.github.io

I would recommend deleting all lists (which you can do when u try to delete 1 list, an option for all comes up) as the old lists basically don't work and arent importable to the new version

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
