### ISSUE TITLE
YASB 2.5 X-wing builder 

### ISSUE THREAD

**Issue by VahanKalOrdo** [raithos/xwing#980]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

Isen't it an error that under Seperatist - Hyena Bomber
That the Init one has a Sensor Upgrade but no Payload upgrade

Whereas the Init 3 has no Sensor upgrade but has the payload upgrade

just an observation

**Comment by Patschke** [comment]
For me everything seems to be correct according to the [official pdfs](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/62150240368e122d0a8a1219/1645544001070/Ship_Points_Jan22.pdf)

I have a question to you: What else could we've done, that would result in you spending 1 minute checking the answer to your question yourself? In fact, creating a github account and writing this message (while ignoring the `Note 1: Make sure that this is a bug and not a misinterpetation of the rules!` part) surely took longer than it would've taken you to open up google. We are honestly interested in feedback, and aim for this to be as easy as possible - since we want to catch bugs and improve YASB as quickly as possible. However, it's quite annoying how many error/bug reports we lately have that are in fact not reporting any mistake. So my question is: Where should we add what kind of information, to get people check the rules themself first, before filing an issue here - without deterring people to report actual bugs?
