### ISSUE TITLE
"Fancy Printouts" have tiny text

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#988]
With the move to 2.5, there are more upgrades.  I've been printing out "Fancy" lists on YASB so I don't have to get cards out for a quick game.

However, the text is tiny.   Pulling out my calipers, once printed on 8.5" x 11" paper (via browser print dialog), the Ability text for a pilot ended up at 1.6mm high, which is somewhere around a 6 pt font.

As a comparison, standard pilot cards have ~2.4mm high text, around 10pts, with official promo cards at ~1.8mm, around 8 pt.  The promo cards also also hard to read.

I'd recommend going up to 10pt font, at least 8pt for all ability text.

**Comment by raithos** [comment]
so im not sure this is something i will adjust, the font hasn't been changed in the entire time i've had yasb (so it was like this in 1.0 as well), and this is the first complaint ive heard about the font being too small. I know countless people who do exactly what youve done, and not heard this before, but i have seen on occasion that depending on your printer settings for the font to be reduced as a bug, but i havent been able to find out how that happens. ive found that adjusting the margins can get the font to the correct size sometimes, but again, no idea whats causing it.

**Comment by covertsonic** [comment]
I experienced this problem myself; I had to reduce the margins to "no margins" when printing.  I printed out 300+ pages of each quick build card for the ships I have, and this is what my playgroup uses (so we don't have to mess around with squad points and finding the upgrade cards).

**Comment by raithos** [comment]
Ok, I've done some more research and testing, it looks like this is an issue when printing to specific printers, when exporting to pdf via print everything looks fine. Since I am not going to create use cases for every printer in the world, and there is a solve by changing the scaling to manual as @covertsonic mentions, I'm going to close this as will not fix.

that being said, i'll probably look more closely at the printing formats, now that we have more upgrades, efficiency is important for spacing
